### PR TITLE
Add GetJobCache function from releaselib.sh

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Due to the migration of the set_build_version function from the release
lib we now convert the get_job_cache function to a golang based
implementation. The signature of the function has changed that we do not
write the results into a directory any more and directly return a new
tpye `JobCache`, which is a dictionary for build numbers and versions.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
- Added `gcp.GSUtil()` function to run GCP commands
- Added `release.GetJobCache()` method to retrieve the job cache for a job name
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by saschagrunert** [comment]
Ping @kubernetes/release-managers for review. I know it's kinda lot of changes but I'd like to continue somehow with the port of releaselib.sh.

**Comment by tpepper** [comment]
I'm behind on reviews and swamped this week, but will try to review and definitely want to see progress continue against releaselib.sh

**Comment by justaugustus** [comment]
/lgtm
/approve
/hold cancel

@saschagrunert -- Let's iterate on this.
I don't have time for a thorough review, but as this code isn't in use yet, and its shape will likely change, I don't want to block progress more than we have already.

**Pull request merged**
