### PR TITLE
bump cosign to v2.0.2

### PR DESCRIPTION
**Pull request by bobcallaway**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Updates a dependency on cosign to the latest release

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

NONE

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by cpanato** [comment]
Thanks @bobcallaway can you check if you sign the easy cla? 🙂

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
