### PR TITLE
Make relnotes work on fedora

### PR DESCRIPTION
**Pull request by pigmej**
Added case statement with `lsb_release -si` to check Feodra OR Ubuntu.

### CODE REVIEW

**Comment by david-mcmahon** [comment]
Thanks for the patch.  There 's a good deal of dup code here.  Why not set values based on the platform and then just $replace them in a single flow of the original logic?

**Comment by pigmej** [comment]
@david-mcmahon I can rework that but there will be still problem with this special repo for ubuntu.

**Comment by pigmej** [comment]
@david-mcmahon updated that's what you meant?

**Comment by david-mcmahon** [comment]
Fair enough.  LGTM.

**Pull request merged**
