### PR TITLE
Always ask user before creating the PR

### LINKED ISSUE #2075: `krel release-notes --create-draft-pr` create the PR without asking
#### What happened:
Trying to run command `krel release-notes --create-draft-pr --fork=cici37` to create release notes draft PR.
The PR is created without providing option to manually create pr later and skipped the option of editing the release notes as well.
Ref: the [PR](https://github.com/kubernetes/sig-release/pull/1578) created accidentally.

#### What you expected to happen:
When it reaches to the point of creating the PR, an option should be provided to skip raise the PR or manually raise the PR. It should also provide the option to edit the release notes.

#### How to reproduce it (as minimally and precisely as possible):
Install krel and try with command `krel release-notes --create-draft-pr --fork=yourfork`

#### Anything else we need to know?:
When I met this issue, I am at the time that the previous release notes pr has been raised/merged, and the next release tag hasn't been created.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
User will always be asked to check if a PR needs to be raised.

#### Which issue(s) this PR fixes:
Fixes #2075 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
cc @pmmalinov01

**Comment by puerco** [comment]
@cici37 sorry I missed this earlier! Thanks a lot, this is one feature I wanted to add for some time now :)
/lgtm
/approve

**Comment by cici37** [comment]
Thank you for reviewing 😊

**Pull request merged**
