### PR TITLE
relnotes_v2: Promote to default strategy of listing release notes

### LINKED ISSUE #2241: relnotes: Promotion of `--list-v2` to be default behavior
#### What would you like to be added:

#1888 introduces `--list-v2` flag for release notes with performance improvements and bug fix. This has been the preferred method for collecting release notes for one (and a half-ish) release cycle.

I personally feel comfortable with promoting this into default behavior and begin "fix and roll forward" for any bug which shows up in the future, thought I would like to solicit feedback on this process and how people feel / think with regards to timeline.

#### Why is this needed:

- Cut down variations and simplify `krel` to the necessary lines of code.
- I'm reviving efforts to #1889 which was abandoned for the past few months, which would benefit from having this resolved.

/cc puerco cici37 pmmalinov01

### PR DESCRIPTION
**Pull request by wilsonehusin**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR proposes v2 implementation of listing release notes to be the default behavior.

#### Which issue(s) this PR fixes:

Fixes #2241
Supersedes #2271

#### Special notes for your reviewer:

- Hopefully the changeset does not scare you away – most of the changes are in `testdata/`, so one conclusion we can draw here is that "we are making less API calls for the more accurate result" :tada: 
- I recommend reviewing by commits, because I wrote descriptive commit messages and purposefully excluded the `testdata/` deletion and addition into their own commits.

#### Does this PR introduce a user-facing change?

```release-note
Changelog / release notes generation now uses ListV2 strategy by default. Previous behavior can still be used by invoking --list-v1 flag.
```

### CODE REVIEW

**Comment by wilsonehusin** [comment]
I think there is something that I don't get correctly about recording the `testdata/` still 🤔 

Seems like upon recording, krel attempted to create a release note as if current head of `release-1.16` branch as v1.16.3, which is not true.

Any advice?

**Comment by puerco** [comment]
Hey Wilson, do you mean because this test is running the gatherer at 1.16.3 ?
https://github.com/kubernetes/release/blob/22ceeee84f182854e685d1adef3c65ddc4a56637/cmd/krel/cmd/changelog_test.go#L49-L52

**Comment by wilsonehusin** [comment]
> Hey Wilson, do you mean because this test is running the gatherer at 1.16.3 ?

Oops sorry it wasn't clear -- I was using `TestNewPatchRelease` as a sample because it would have cherry pick commits, which in turn samples from 1.16.3

**Comment by CecileRobertMichon** [comment]
Hi @wilsonehusin, @puerco and I did a little investigation after I reported that I was having issues with missing commits when running the release-notes tool from a patch release to a minor version  (eg. v1.1.2 to v1.2.0) as the release-notes tool looks at chronological order which means commits that were made _before_ a patch release tag but _not included_ in said tag would be excluded.

For example, between v1.1.2 and v1.2.0 of CAPZ, I'm expecting 106 merge commits:
```
git rev-list v1.1.2..v1.2.0 --merges | wc -l
     106
 ```

But the release-notes tool only looks at 56:
```
export GIT_ORG_NAME=kubernetes-sigs
➜  cluster-api-provider-azure git:(release-1.2) export RELEASE_BRANCH=release-1.2
➜  cluster-api-provider-azure git:(release-1.2) export PREVIOUS_TAG=v1.1.2
➜  cluster-api-provider-azure git:(release-1.2) export RELEASE_TAG=v1.2.0
➜  cluster-api-provider-azure git:(release-1.2) hack/tools/bin/release-notes --org $GIT_ORG_NAME --repo $GIT_REPO_NAME --branch $RELEASE_BRANCH  --start-rev $PREVIOUS_TAG --end-rev $RELEASE_TAG
INFO Cloning/updating repository kubernetes-sigs/cluster-api-provider-azure
INFO Using found start SHA: 94fb411d2d90541ba2020aae969ce2fadf57d451
INFO Using found end SHA: 07fbd76dbd7945edb2ef8af968d4693d6dff35f2
INFO Using output format: markdown
INFO Gathering release notes
INFO Starting to process commit 1 of 56
```

When I switch to using --list-v2, it actually fixes that behavior and looks at the right commits:

```
hack/tools/bin/release-notes --org $GIT_ORG_NAME --repo $GIT_REPO_NAME --branch $RELEASE_BRANCH  --start-rev $PREVIOUS_TAG --end-rev $RELEASE_TAG --list-v2
INFO Cloning/updating repository kubernetes-sigs/cluster-api-provider-azure
INFO Using found start SHA: 94fb411d2d90541ba2020aae969ce2fadf57d451
INFO Using found end SHA: 07fbd76dbd7945edb2ef8af968d4693d6dff35f2
INFO Using output format: markdown
INFO Gathering release notes
WARN EXPERIMENTAL IMPLEMENTATION ListReleaseNotesV2 ENABLED
INFO will stop at fff537114ca8348c65484cc5f5ef551f2851f2db
INFO processing release notes for 106 commits
106 / 106 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 27 p/s
INFO finished gathering release notes in 4.676407168s
INFO Got 45 release notes, performing rendering
INFO Setting up repository github.com/kubernetes-sigs/cluster-api-provider-azure
INFO Retrieving modules of 94fb411d2d90541ba2020aae969ce2fadf57d451
INFO Retrieving modules of 07fbd76dbd7945edb2ef8af968d4693d6dff35f2
INFO 476 modules found
INFO 13 modules added
INFO 80 modules changed
INFO 11 modules removed
INFO Release notes written to file: /var/folders/11/f41_16k56w1cxnpw5jwjks0h0000gn/T/release-notes-2287834190
```

So I wanted to share this in case this wasn't already one of the motivations for doing this v2 work, it actually fixes this issue for us and looks like it's running a lot faster too 🚀 

I'll switch to using v2 in CAPZ and report back if we run into any issues. 

cc @shysank

**Comment by CecileRobertMichon** [comment]
Small edit on my comment above:

It looks like using --list-v2 is actually including commits that were cherry-picked into the patch release as well. This makes sense since we're using a forked release branch, the commits in the main branch are different from the commits in the release branch, even though the release note for the PR is the same. Not sure if there's a way around this. I'd rather see commits re-included than dropping commits like before so overall still an improvement.

**Comment by wilsonehusin** [comment]
Hello @CecileRobertMichon, good to hear that! I'll start with apologies for all the messy, abandoned progress around this work. In short, I have not been able to allocate the time to refactor and make the implementation reasonable enough.

The blocker from what I recall is that this still doesn't implement the PR body discovery on cherry-picked commits. I'm not sure how much of the k/k process is relevant in CAPZ, but from what I understand, the k/k cherry-pick process is roughly as follows:

1. get changeset PR to k/k primary (`master`) branch first
2. after that's merged, cherry-pick the PR to `release-*` branches

At the moment, there is no enforcement in k/k for PR 2 to have release notes, as long as PR 1 has release notes. This is okay because v1 implementation traverses through all related PR numbers, which eventually parses the PR 1 body from the commit message of PR 2.

However, v2 _gives up_ the moment it doesn't find release notes on PR 2. I was struggling to implement the traversal in way that is reasonably testable, and eventually this effort somewhat fell behind.

I'm happy to chat and perhaps collaborate on getting this through, though unfortunately at the moment, I'm personally too occupied to perform the refactor and fixes by myself 😢

**Comment by CecileRobertMichon** [comment]
>  The blocker from what I recall is that this still doesn't implement the PR body discovery on cherry-picked commits. I'm not sure how much of the k/k process is relevant in CAPZ

In CAPZ we use the k8s-infra-cherrypick-robot  cherry-pick plugin to cherry-pick PRs to release branches and AFAIK the bot does carry over the release note block in the cherry-pick PR so that shouldn't be a blocker for CAPZ. For example, [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1964) was opened by the bot to cherry-pick [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1948) and included the same release note in PR body, so it would be included in release notes when generating release notes. It doesn't seem to carry over the `kind` labels so release notes would all be "uncategorized" though.

**Comment by wilsonehusin** [comment]
```
Error:      	"\n\n  \n    \n    \n    \n    \n  \n  \n    
v1.18.0-alpha.3
\n
Changelog since v1.25.0-alpha.0
\n\n  \n" does not contain "\n
Changes by Kind
\n
Deprecation
\n
\n
Kubeadm: kube-dns is deprecated and will not be supported in a future version
```

🤔 why is it pulling v1.25.0-alpha.0 in [`TestNewAlphaRelease`](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2313/pull-release-integration-test/1516654169077846016)?

**Comment by wilsonehusin** [comment]
Okay the last remaining test failure is blocked by the fact that we're not taking into account `LatestGitHubTagsPerBranch` to be mock-able with record / replay.

https://github.com/kubernetes/release/blob/c969918994660a52fcd124fc576d4e69ebee0540/pkg/changelog/changelog.go#L142-L143

https://github.com/kubernetes/release/blob/c969918994660a52fcd124fc576d4e69ebee0540/pkg/changelog/impl.go#L126-L128

The second snippet in `impl.go`, we need to take into account record-able scenarios.

**Comment by wilsonehusin** [comment]
Working on this, blocked by https://github.com/kubernetes-sigs/release-sdk/pull/60

**Comment by wilsonehusin** [comment]
I'm expecting [the current failures](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2313/pull-release-integration-test/1516951780083109888) to be resolved once https://github.com/kubernetes-sigs/release-sdk/pull/60 is merged.

I guess I'm paying the price of delaying the work on this instead of finishing it all up before we branched out to `release-sdk` and `release-utils` 🙃

**Comment by wilsonehusin** [comment]
Okay, I believe this is ready for review now. Thanks for the patience!

**Comment by puerco** [comment]
OK, back on this. @wilsonehusin my firest question is: why are you removing the test files? Shouldn't we expect them to still work with v2?

**Comment by wilsonehusin** [comment]
> why are you removing the test files? Shouldn't we expect them to still work with v2?

not exactly — these tests files were previously generated retroactively. as such, the test files we had here has more release notes than the original changelog (which is the bug fixed by v2)

also, just to make sure you're aware, the tests files were removed and then regenerated. now regenerating it multiple times should end up with the same results still.

**Comment by wilsonehusin** [comment]
(i will address rebase after / together with reviews so we don't have too much noise in here)

**Pull request closed without merging**
