### PR TITLE
Remove hyperkube references

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup deprecation

#### What this PR does / why we need it:

The next v1.18 release (v1.18.19) on 5/7/21 will bring v1.18 to End of Life: https://github.com/kubernetes/sig-release/pull/1532
With that, we'll need to remove any remaining references to hyperkube.

Tracking issue: https://github.com/kubernetes/release/issues/2017

#### Does this PR introduce a user-facing change?

```release-note
Remove hyperkube references
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold until [v1.18 and hyperkube is EOL (on 5/12/21)](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#118)
cc: @kubernetes/release-engineering 

/override pull-release-image-debian-hyperkube-base
ref: https://github.com/kubernetes/test-infra/pull/21941

**Comment by justaugustus** [comment]
The remaining hyperkube references are removed in https://github.com/kubernetes/release/pull/2019.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
It's been real, hyperkube!
/hold cancel
ref: https://groups.google.com/u/1/g/kubernetes-dev/c/c9mDzTsHnxM

**Comment by justaugustus** [comment]
(Rebasing...)

**Comment by justaugustus** [comment]
/override pull-release-image-debian-hyperkube-base
(This job is in the midst of being removed in https://github.com/kubernetes/test-infra/pull/21941.)

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by puerco** [comment]
/lgtm
THanks!!!

**Pull request merged**
