### PR TITLE
Provenance attesattion for artifacts

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?

/kind feature
#### Which issue(s) this PR fixes:

This PR adds the final bit to make all artifacts in the release bucket SLSA1 compliant. We still have to publish the attestations for the container images but we now have a way to check the provenance of all released artifacts.

The final in-toto attestation is composed by parsing the release SBOM, adding the data from the artifacts and then reusing the SLSA predicate from the staging provenance bucket. 

Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>

#### Special notes for your reviewer:

Part of https://github.com/kubernetes/release/issues/2267

Test run: https://console.cloud.google.com/cloud-build/builds;region=global/66ca2089-2c31-4bdb-8cdd-93342681d166?project=kubernetes-release-test
(Se sample provenance data attached bellow)

#### Does this PR introduce a user-facing change?
```release-note
Releases now publish a provenance attestation with a SLSA 0.1 predicate describing all artifacts in the release bucket. 
```

### CODE REVIEW

**Comment by puerco** [comment]
Sample attestation:  [provenance.json.gz](https://github.com/kubernetes/release/files/7459956/provenance.json.gz)

**Comment by puerco** [comment]
Updated provcenance data with paths to actual release bucket locations [provenance.json.gz](https://github.com/kubernetes/release/files/7460174/provenance.json.gz)
:

**Comment by palnabarun** [comment]
/cc
(will have a look on Saturday)

**Review by palnabarun — CHANGES_REQUESTED** [review]
Just a few small nits, LGTM otherwise!

Great work as always! 💯 

I had fun reading through the SLSA Provenance specification and understanding it. Looking forward to the update to v0.2 as well. :)

**Comment by puerco** [comment]
Yay, thank a lot @palnabarun , the two nits are addressed and we are should be ready to get the provenance attestations out of the build after we cut the next releases. The SLSA 0.2 types have not yet merged yet: https://github.com/in-toto/in-toto-golang/pull/156  but ill start working to move to 0.2 based on @priyawadhwa 's PR.
Thank you!

**Comment by palnabarun** [comment]
Thank you, Adolfo!

**Comment by cpanato** [comment]
late /lgtm

thanks for the hard work on this

**Pull request merged**
