### PR TITLE
pkg/cip: Add `cli` package

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup feature

#### What this PR does / why we need it:

(Commands were copied in from https://github.com/kubernetes-sigs/k8s-container-image-promoter/tree/455e8e6a6d2888de200d1fdadf2ee0e3d5c7d1d3.)

The `cli` package holds configurable options and command function logic
for the commands in the k8s-container-image-promoter repo.

This will allow us to:
- refactor/integrate the commands without updates to the cip repo
- start pulling functionality into `kpromo`
- further decrease reliance on bazel

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @hasheddan @saschagrunert @cpanato 
cc: @kubernetes/release-engineering 

#### Special notes for your reviewer:

This is roughly a 1:1 copy of https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/282, with the relevant functions/types exported, so little review is required.

#### Does this PR introduce a user-facing change?

```release-note
- pkg/cip: Add `cli` package

  The `cli` package holds configurable options and command function logic
  for the commands in the k8s-container-image-promoter repo.
  
  This will allow us to:
  - refactor/integrate the commands without updates to the cip repo
  - start pulling functionality into `kpromo`
  - further decrease reliance on bazel

  (Commands were copied in from https://github.com/kubernetes-sigs/k8s-container-image-promoter/tree/455e8e6a6d2888de200d1fdadf2ee0e3d5c7d1d3.)
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
