### PR TITLE
Remove bazel from k/release

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup deprecation
/area dependency

#### What this PR does / why we need it:

Remove bazel from k/release

This PR has been open since July, attempting to navigate various bazel errors and preventing dependency updates for quite some time.

After discussing with the other @kubernetes/release-engineering in https://kubernetes.slack.com/archives/CJH2GBF7Y/p1600353676142700, we can see no clear benefit for having bazel in the repo, so I'm changing the direction of this PR to remove it.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Supersedes https://github.com/kubernetes/release/pull/1255.

#### Does this PR introduce a user-facing change?

```release-note
- Remove bazel from k/release
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hey @justaugustus, do you think we can fix the CI somehow? :) let’s bring this change in.

**Review by hasheddan — APPROVED** [review]
/lgtm

🎉🎉🎉

**Pull request merged**
