### PR TITLE
Migrate `gh2gcs` to the promotion tooling repo

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup design

#### What this PR does / why we need it:

While working on the file promotion automation (https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/413) and chatting with @justinsb, I realized that `gh2gcs` is a promotion tool and should live alongside the rest for potential integrations (like exposing GitHub as a `filestore` for promotion).

- Migrate `gh2gcs` to the promotion tooling repo
- Migrate pkg/{git,github,release/regex} to sigs.k8s.io/release-sdk
- Update import paths for sigs.k8s.io/release-sdk
- generated: Run `go mod tidy`

Signed-off-by: Stephen Augustus <foo@auggie.dev>

ref: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/423, https://github.com/kubernetes-sigs/release-sdk/pull/3, https://github.com/kubernetes-sigs/release-sdk/releases/tag/v0.2.0

#### Does this PR introduce a user-facing change?

```release-note
- Migrate `gh2gcs` to the promotion tooling repo
- Migrate pkg/{git,github,release/regex} to sigs.k8s.io/release-sdk
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @puerco @cpanato @ameukam @Verolop
cc: @kubernetes-sigs/release-engineering

**Comment by puerco** [comment]
+69 −9,040 :)
/lgtm

**Comment by justaugustus** [comment]
(this is broken into commits separating generated changes and search/replace things, so it should be easy to intuit what's happening)

**Comment by justaugustus** [comment]
> +69 −9,040 :)

Niiiiiiiiiiiiiiice.

**Pull request merged**
