### PR TITLE
Add goreleaser actions

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Add a GitHub action to release the `release-notes` tool as well as `krel` via goreleaser.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL @kubernetes/release-engineering

**Comment by xmudrii** [comment]
@saschagrunert There's a (strong) preference from SIG Testing and GitHub Admins to use Prow as much as possible. Why do we use GH Actions here instead of using Prow? We could more-or-less easily do everything in Prow.

**Comment by saschagrunert** [comment]
> @saschagrunert There's a (strong) preference from SIG Testing and GitHub Admins to use Prow as much as possible. Why do we use GH Actions here instead of using Prow? We could more-or-less easily do everything in Prow.

We already use goreleaser, for example in zeitgeist: https://github.com/kubernetes-sigs/zeitgeist

**Comment by saschagrunert** [comment]
@cpanato addressed everything. PTAL again.

**Review by cpanato — APPROVED** [review]
cool

lets run a release to try this out!

/lgtm

**Comment by saschagrunert** [comment]
@cpanato can we lift the hold?

**Comment by cpanato** [comment]
/unhold

sorry did not notice that :/

**Pull request merged**
