### PR TITLE
Increase .bazelrc test timeout

### PR DESCRIPTION
**Pull request by hasheddan**
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

pull-release-test is flaking regularly due to timeout. This
increases the test timeout from 1800 to 2000 to address it.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/89197

#### Special notes for your reviewer:

This timeout increase is somewhat arbitrary. We should observe and see if it is enough to reduce flakes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

cc @saschagrunert @droslean @justaugustus

### CODE REVIEW

**Comment by hasheddan** [comment]
@saschagrunert I have not observed this timeout since the dashboards were moved, do you think it is safe to close this one?

**Comment by justaugustus** [comment]
/close
Let's reassess if there are still issues.

**Pull request closed without merging**
