### PR TITLE
Update cri-tools to 1.11.1.

### PR DESCRIPTION
**Pull request by Random-Liu**
Update cri-tools to 1.11.1.

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
Also see https://github.com/kubernetes/kubernetes/pull/66152.

**Comment by luxas** [comment]
cc @calebamiles @timothysc

**Comment by chuckha** [comment]
this looks good to me, can you take a look @calebamiles?

**Pull request merged**
