### PR TITLE
Remove anago

### LINKED ISSUE #1673: [krel] Implement krel stage/release
#### krel stage

- [x] Check Prerequisites (cc @markyjackson-taulia)
- [x] Set Build Candidate (cc @rajibmitra, https://github.com/kubernetes/release/issues/1536)
- [x] Set Release Values / Generate Release Version
- [x] Prepare Workspace (cc @saschagrunert, https://github.com/kubernetes/release/pull/1677)
- [x] Tag repository
- [x] Build
- [x] Generate changelog
- [x] Stage artifacts

#### krel release

The anago `release` part is less complex than the `stage`-ing logic, so we can start with the easy bits first and refactor anago on top of it.

In the end, `krel release` should (see https://github.com/kubernetes/release/blob/master/cmd/krel/cmd/release.go)
- [x] Check Prerequisites (cc @markyjackson-taulia)
- [x] Set Build Candidate (cc @rajibmitra, https://github.com/kubernetes/release/issues/1536)
- [x] Set Release Values / Generate Release Version
- [x] Prepare Workspace (cc @saschagrunert, https://github.com/kubernetes/release/pull/1677)
- [x] Push Artifacts
- [x] Push Git Objects (cc @puerco, https://github.com/kubernetes/release/pull/1658)
- [x] Announce (https://github.com/kubernetes/release/pull/1697)
  - [x] Create publishing bot issue
- [x] Update GitHub release  (cc @puerco, https://github.com/kubernetes/release/pull/1704 https://github.com/kubernetes/release/pull/1789)
- [x] Archive (@puerco https://github.com/kubernetes/release/pull/1768  https://github.com/kubernetes/release/pull/1769)

Reference document:
https://docs.google.com/document/d/1NT5ouEcV4MXBWW3wO-RJDVnoMPyJeGlONB9-wxI857I/edit?usp=sharing

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This is the patch everyone is waiting for! :heart: We finally remove `anago` as well as all referencing scripts and documentation to it.

#### Which issue(s) this PR fixes:

Closes #1673 

#### Special notes for your reviewer:

Requires ~~#1763~~, ~~#1764~~, ~~#1769~~ as well as #1789
Requires manual testing, too.

/hold

#### Does this PR introduce a user-facing change?

```release-note
Removed `anago` and all referencing dependencies, for example the `krel anago …` and the `krel gcbmgr` subcommands.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
#### Manual testing

- :heavy_check_mark: Stage beta:
  https://console.cloud.google.com/cloud-build/builds/d08ce35d-694e-4604-a8bf-73aec002070a?project=kubernetes-release-test
- :hourglass: Release beta:
  https://console.cloud.google.com/cloud-build/builds/db6cd82a-16ce-407d-bb2b-a92130de1cab?project=kubernetes-release-test

**Comment by puerco** [comment]
:open_mouth:  omg. The day has come.

**Comment by justaugustus** [comment]
OMGOMGOMG

**Comment by xmudrii** [comment]
**Manual testing**

* :hourglass_flowing_sand: Stage - alpha (**expected to fail because beta already exists**): https://console.cloud.google.com/cloud-build/builds/0fe393e3-d874-4d77-bb4d-1a6627a8bd81?project=kubernetes-release-test

**Comment by saschagrunert** [comment]
Everything looks good…
/hold cancel

**Review by xmudrii — APPROVED** [review]
/lgtm

:rocket:

**Comment by puerco** [comment]
/lgtm !!

:rocket: :rocket: :rocket:

**Review by hasheddan — APPROVED** [review]
Really nice work @saschagrunert and others :)

/lgtm

**Pull request merged**
