### PR TITLE
Build Go 1.20.4 and 1.19.9 based images

### PR DESCRIPTION
**Pull request by rayandas**
#### What type of PR is this?
/kind feature
/area dependency

#### What this PR does / why we need it:
- Build Go 1.20.4 and 1.19.9 based images
#### Which issue(s) this PR fixes:
Partially fixes: https://github.com/kubernetes/release/issues/3025

#### Does this PR introduce a user-facing change?

```release-note
Build Go 1.20.4 and 1.19.9 based images
```

### CODE REVIEW

**Comment by rayandas** [comment]
cc: @xmudrii

**Comment by cpanato** [comment]
/retest

looks like images are released, lets see, sometimes take a bit of time to be available

**Comment by cpanato** [comment]
thanks !

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
