### PR TITLE
update cosign image and use the ghcr registry

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- update cosign image and use the ghcr registry
/assign @puerco @saschagrunert @xmudrii 
cc @kubernetes/release-managers 

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
humm, one job passed https://console.cloud.google.com/cloud-build/builds;region=global/a3e89815-45dc-4e34-81a4-47cba3ae0193?project=k8s-staging-releng-test

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
i think i know the issue, but i need to reproduce locally

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
