### PR TITLE
Revert recent changes to stabilize CI and release tooling

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
`pull-release-verify` is failing because the shellchecks have been undone. This is expected:
/override pull-release-verify

**Comment by hoegaarden** [comment]
Can you please explain how this PR was generated? Is it just revertign back to `v0.1.0` or are there other patches involved?

From what I can see at least 2 things are missing:
- [ ] The new token in the GCB manifests
- [ ] The trimming of leading/trailing whitespaces of the token

**Comment by justaugustus** [comment]
@hoegaarden -- here I've gone back further than `v0.1.0` (pre-shellcheck) to 4f2ca563a0db3a58eb2186f7ae0716c29916830d, which was a commit prior to the cut of `v1.15.0`.

```
git checkout -b time-travel
git reset 4f2ca563a0db3a58eb2186f7ae0716c29916830d
git reset HEAD OWNERS* README.md build/godep-builder/Dockerfile cmd/release-notes/README.md debian/bionic/ gcb/ pkg/notes/ rpm/kubelet.spec
Unstaged changes after reset:
M	OWNERS
M	OWNERS_ALIASES
M	README.md
M	build/godep-builder/Dockerfile
M	cmd/release-notes/README.md
M	debian/bionic/cri-tools/debian/changelog
M	debian/bionic/cri-tools/debian/control
M	debian/bionic/cri-tools/debian/copyright
M	debian/bionic/cri-tools/debian/rules
M	gcb/release.yaml
M	gcb/stage.yaml
M	pkg/notes/notes.go
M	pkg/notes/notes_test.go
M	rpm/kubelet.spec
git commit --signoff
git push -f a time-travel
```

The new token is not included in this commit because it already exists on `master`.
We still need to add the whitespace fix, which I can cherry pick in a separate PR.

**Comment by idealhack** [comment]
changes between `v0.1.0` and this PR: https://github.com/kubernetes/release/compare/v0.1.0...justaugustus:time-travel

**Comment by justaugustus** [comment]
Thanks for posting that, @idealhack!

**Comment by justaugustus** [comment]
Setting shellcheck job to optional again: https://github.com/kubernetes/test-infra/pull/13316

**Comment by justaugustus** [comment]
Whitespace trim follow-up is here: https://github.com/kubernetes/release/pull/815

**Comment by justaugustus** [comment]
Follow up items here: #816

**Comment by xauthulei** [comment]
@justaugustus, Do have any plan to merge the discard PR code changes during we brought `pull-release-verify`. Meanwhile, for PR #752, I have wished to fix bugs and do enhancement(Is this  changes reasonable) .

**Pull request merged**
