### PR TITLE
Add GCS bucket to release artifacts push

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
We lost the bucket due to one of the latest refactors. This commit
adds it back to the target path.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/lgtm
/approve

ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1605647494040700?thread_ts=1605636625.012900&cid=CJH2GBF7Y

**Comment by onlydole** [comment]
Thank you, team!

**Pull request merged**
