### PR TITLE
.github: Add dependency review action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- https://github.blog/2022-04-06-prevent-introduction-known-vulnerabilities-into-your-code/

This helps prevent including dependencies that have vulnerabilities.

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@justaugustus 👀

**Review by justaugustus — CHANGES_REQUESTED** [review]
Thanks for adding this, @naveensrinivasan!
(Merging in some code suggestions as well.)

/retitle .github: Add dependency review action
/ok-to-test

**Review by justaugustus — APPROVED** [review]
/release-note-none

**Pull request merged**
