### PR TITLE
upgrade to go1.22

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- upgrade to go1.22

/hold for test-infra job update

/assign @saschagrunert @xmudrii @puerco 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
upgrade to go1.22
```

### CODE REVIEW

**Comment by cpanato** [comment]
test-infra job update https://github.com/kubernetes/test-infra/pull/32273

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
