### PR TITLE
debian-builder: use golang:1.16.7-buster as the base image

### PR DESCRIPTION
**Pull request by palnabarun**
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1629401120230000?thread_ts=1629353341.198900&cid=CJH2GBF7Y

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by puerco** [comment]
/lgtm
/approve

Thank you :)

**Review by justaugustus — APPROVED** [review]
Thanks @palnabarun!

**Pull request merged**
