### PR TITLE
Rename SetClient to SetImpl for stage/release impls

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
"Client" seems the wrong terminology in that case, because we already
have `…Impl` interfaces as well as structs. This is just a small cleanup
for sake of consistency.
#### Which issue(s) this PR fixes:

Refers to #1673 
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
@justaugustus tide seems stuck here.

**Comment by justaugustus** [comment]
This may need a rebase and the mocks regenerated.

**Comment by saschagrunert** [comment]
> This may need a rebase and the mocks regenerated.

Done :+1:

**Pull request merged**
