### PR TITLE
Verify `cosign` signatures of distroless base images

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency security

#### What this PR does / why we need it:

- Verify cosign signatures of distroless base images
- go-runner: Build v2.3.1-go1.16.3-buster.1 image
- go-runner: Build v2.3.1-go1.15.11-buster.1 image

From @dekkagaijin in https://github.com/kubernetes/release/pull/2011:

This'll ensure that the `distroless` base images were built on trusted infrastructure

```
$ docker run -it gcr.io/projectsigstore/cosign/ci/cosign@sha256:c581a4f0f6dd158220fa05d2351d8015f969b68de5c61d52c41478fae84e7064 -- verify -key https://raw.githubusercontent.com/GoogleContainerTools/distroless/main/cosign.pub gcr.io/distroless/base:latest
Unable to find image 'gcr.io/projectsigstore/cosign/ci/cosign@sha256:c581a4f0f6dd158220fa05d2351d8015f969b68de5c61d52c41478fae84e7064' locally
gcr.io/projectsigstore/cosign/ci/cosign@sha256:c581a4f0f6dd158220fa05d2351d8015f969b68de5c61d52c41478fae84e7064: Pulling from projectsigstore/cosign/ci/cosign
5dea5ec2316d: Already exists
bb771d6dc9a1: Already exists
9127c3610b7e: Already exists
72164b581b02: Already exists
6fe218878cac: Pull complete
Digest: sha256:c581a4f0f6dd158220fa05d2351d8015f969b68de5c61d52c41478fae84e7064
Status: Downloaded newer image for gcr.io/projectsigstore/cosign/ci/cosign@sha256:c581a4f0f6dd158220fa05d2351d8015f969b68de5c61d52c41478fae84e7064

Verification for gcr.io/distroless/base:latest --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":""},"image":{"docker-manifest-digest":"sha256:6ec6da1888b18dd971802c2a58a76a7702902b4c9c1be28f38e75e871cedc2df"},"type":"cosign container signature"},"optional":null},{"critical":{"identity":{"docker-reference":""},"image":{"docker-manifest-digest":"sha256:6ec6da1888b18dd971802c2a58a76a7702902b4c9c1be28f38e75e871cedc2df"},"type":"cosign container signature"},"optional":null},{"critical":{"identity":{"docker-reference":""},"image":{"docker-manifest-digest":"sha256:6ec6da1888b18dd971802c2a58a76a7702902b4c9c1be28f38e75e871cedc2df"},"type":"cosign container signature"},"optional":null},{"critical":{"identity":{"docker-reference":""},"image":{"docker-manifest-digest":"sha256:6ec6da1888b18dd971802c2a58a76a7702902b4c9c1be28f38e75e871cedc2df"},"type":"cosign container signature"},"optional":null},{"critical":{"identity":{"docker-reference":""},"image":{"docker-manifest-digest":"sha256:6ec6da1888b18dd971802c2a58a76a7702902b4c9c1be28f38e75e871cedc2df"},"type":"cosign container signature"},"optional":null}]
```

#### Special notes for your reviewer:

I did a git oops when pushing updates to @dekkagaijin's branch, which accidentally closed https://github.com/kubernetes/release/pull/2011.

#### Does this PR introduce a user-facing change?

```release-note
- Verify cosign signatures of distroless base images
- go-runner: Build v2.3.1-go1.16.3-buster.1 image
- go-runner: Build v2.3.1-go1.15.11-buster.1 image
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @hasheddan @puerco 
/cc @dekkagaijin @dlorenc
cc: @kubernetes/release-engineering 
/area release-eng/security

**Review by dekkagaijin — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
(needs re-/lgtm; had to update the image revision numbers)

**Comment by dekkagaijin** [comment]
Thanks, @justaugustus

🎉🦜🎉

**Comment by q464q** [comment]
可以拉取嗎？謝謝

**Comment by rjb4standards** [comment]
Does cosign verify that the signer of a container has been authorized by the original supplier of the container to sign on their behalf? How do you verify that the signer and original supplier form a trusted relationship?

**Comment by sopalsuemae** [comment]
Sopalsuemae นายซอปาลซือแม

**Comment by dekkagaijin** [comment]
@rjb4standards That's a complicated question, but in this specific case k8s is pinning the trusted public key that has been checked in to the distroless repo: https://github.com/GoogleContainerTools/distroless/blob/main/cosign.pub

**Pull request merged**
