### PR TITLE
Refresh debian-base image

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- drop debian-base buster it is not in use anymore 
- rebuild debian-base bulleyes to refresh the image 

/assign @saschagrunert @xmudrii @ameukam 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/release/issues/2883

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Comment by acumino** [comment]
Image created after this PR is `gcr.io/k8s-staging-releng-test/debian-base-arm64:bullseye-v1.4.3`.
Should not its registry be `registry.k8s.io`?

**Comment by cpanato** [comment]
> bullseye-v1.4.3
the image promotion is here https://github.com/kubernetes/k8s.io/pull/4813

**Comment by cpanato** [comment]
> Image created after this PR is `gcr.io/k8s-staging-releng-test/debian-base-arm64:bullseye-v1.4.3`. Should not its registry be `registry.k8s.io`?

the image promotion is here https://github.com/kubernetes/k8s.io/pull/4813

**Comment by acumino** [comment]
> > Image created after this PR is `gcr.io/k8s-staging-releng-test/debian-base-arm64:bullseye-v1.4.3`. Should not its registry be `registry.k8s.io`?
> 
> the image promotion is here [kubernetes/k8s.io#4813](https://github.com/kubernetes/k8s.io/pull/4813)

Thanks 👍

**Pull request merged**
