### PR TITLE
Migrate `bom` utility to sigs.k8s.io/bom

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup deprecation

#### What this PR does / why we need it:

Following the merge of https://github.com/kubernetes-sigs/bom/pull/1, the `bom` utility has successfully been migrated to sigs.k8s.io/bom.

This PR:
- removes the associated code from k/release
- adds tombstones/breadcrumbs to the new code/documentation locations for existing consumers

/hold until I cut a release of sigs.k8s.io/bom to use for the remaining import paths
/assign @puerco @cpanato 
cc: @kubernetes/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
- Migrate `bom` utility to sigs.k8s.io/bom
```

### CODE REVIEW

**Comment by justaugustus** [comment]
(Expect test failures since some of the imports are currently broken)

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/assign @puerco @cpanato @jeremyrickard @saschagrunert 
cc: @kubernetes/release-engineering 

/hold cancel
(https://github.com/kubernetes-sigs/bom/releases/tag/v0.1.0 has been cut and import paths updated)

**Comment by justaugustus** [comment]
(Also working on a docs cleanup for `bom` here: https://github.com/kubernetes-sigs/bom/pull/3)

**Comment by puerco** [comment]
Thanks a lot @justaugustus !
/lgtm

**Pull request merged**
