### PR TITLE
kube-cross: Build v1.14.6-1

### PR DESCRIPTION
**Pull request by mkumatag**
#### What type of PR is this?

/kind feature
/area dependency
/priority critical-urgent

#### What this PR does / why we need it:
go1.14.6 announced and needed for the ppc64le platform, announce: https://groups.google.com/g/golang-announce/c/9KNZ5g9tv4o/m/n_CqeNoUBwAJ

/assign @tpepper @saschagrunert @hasheddan @cpanato @dims @BenTheElder
cc: @kubernetes/release-engineering

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kube-cross: Build v1.14.6-1
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Thanks @mkumatag! I've assigned the tracking issue to myself, as the other steps will need to be done by a Release Manager.

/lgtm
/approve

**Comment by mkumatag** [comment]
> Thanks @mkumatag! I've assigned the tracking issue to myself, as the other steps will need to be done by a Release Manager.
> 
> /lgtm
> /approve

 👍

**Comment by mkumatag** [comment]
I see https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-kube-cross/1283974562400178176 job failed to build and push the kube-cross image, not sure how to debug and understand what really failed?! @justaugustus @listx

**Comment by BenTheElder** [comment]
There are more logs per build under the artifacts link

**Comment by BenTheElder** [comment]
Hmmm... Or usually there are ....

**Comment by mkumatag** [comment]
nothing much useful in the artifacts, https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/post-release-push-image-kube-cross/1283974562400178176/

All I have is:
```
2020/07/17 04:00:14 Job "go1.14" failed: error running [gcloud builds submit --verbosity info --config /home/prow/go/src/github.com/kubernetes/release/images/build/cross/cloudbuild.yaml --substitutions _CONFIG=go1.14,_ETCD_VERSION=v3.4.9,_GO_VERSION=1.14.6,_KUBE_CROSS_VERSION=v1.14.6-1,_PROTOBUF_VERSION=3.0.2,_GIT_TAG=v20200717-v0.3.4-58-gcba1d9c --project k8s-staging-build-image --gcs-log-dir gs://k8s-staging-build-image-gcb/logs --gcs-source-staging-dir gs://k8s-staging-build-image-gcb/source gs://k8s-staging-build-image-gcb/source/08754151-d718-4d6d-b07c-e3f100122a04.tgz]: exit status 1
INFO: Display format: "
          table(
            id,
            createTime.date('%Y-%m-%dT%H:%M:%S%Oz', undefined='-'),
            duration(start=startTime,end=finishTime,precision=0,calendar=false,undefined="  -").slice(2:).join(""):label=DURATION,
            build_source(undefined="-"):label=SOURCE,
            build_images(undefined="-"):label=IMAGES,
            status
          )
        "
starting build "b1ed9b0e-ea49-4489-b191-cca8fcfbbd50"

FETCHSOURCE
Fetching storage object: gs://k8s-staging-build-image-gcb/source/1594958375.79-4bd48765999240a7b34bb7d6b5415d1f.tgz#1594958376029170
--------------------------------------------------------------------------------

ID                                    CREATE_TIME                DURATION  SOURCE                                                                                      IMAGES                                                                STATUS
b1ed9b0e-ea49-4489-b191-cca8fcfbbd50  2020-07-17T03:59:36+00:00  9M22S     gs://k8s-staging-build-image-gcb/source/1594958375.79-4bd48765999240a7b34bb7d6b5415d1f.tgz  gcr.io/k8s-staging-build-image/kube-cross-amd64:v1.13.13-2 (+1 more)  SUCCESS
2020/07/17 04:09:00 Successfully built image: gcr.io/k8s-infra-prow-build-trusted/kube-cross-amd64:$_KUBE_CROSS_VERSION gcr.io/k8s-infra-prow-build-trusted/kube-cross-amd64:v20200717-v0.3.4-58-gcba1d9c-go1.13  
2020/07/17 04:09:00 Job "go1.13" completed.
2020/07/17 04:09:00 Failed to run some build jobs: [job "go1.14" failed: error running [gcloud builds submit --verbosity info --config /home/prow/go/src/github.com/kubernetes/release/images/build/cross/cloudbuild.yaml --substitutions _CONFIG=go1.14,_ETCD_VERSION=v3.4.9,_GO_VERSION=1.14.6,_KUBE_CROSS_VERSION=v1.14.6-1,_PROTOBUF_VERSION=3.0.2,_GIT_TAG=v20200717-v0.3.4-58-gcba1d9c --project k8s-staging-build-image --gcs-log-dir gs://k8s-staging-build-image-gcb/logs --gcs-source-staging-dir gs://k8s-staging-build-image-gcb/source gs://k8s-staging-build-image-gcb/source/08754151-d718-4d6d-b07c-e3f100122a04.tgz]: exit status 1]
```

**Comment by justaugustus** [comment]
As this config builds multiple GCB variants concurrently, the individual GCB logs are suppressed in Prow and instead only visible on GCB. You can see links to the individual GCB runs at the start of the Prow job.

Those logs are only visible to those with access to the k8s-staging-build-image project.
(Which is why I mentioned that this process needs to be continued by a Release Manager.)

The actual failure is that the 1.14.6 image is not yet available (which is a common occurrence for new go versions).

I'll fix this up and rebuild the job later today, as we also need kube-cross built for go1.13.14.

**Comment by mkumatag** [comment]
> As this config builds multiple GCB variants concurrently, the individual GCB logs are suppressed in Prow and instead only visible on GCB. You can see links to the individual GCB runs at the start of the Prow job.
> 
> Those logs are only visible to those with access to the k8s-staging-build-image project.
> (Which is why I mentioned that this process needs to be continued by a Release Manager.)
> 
> The actual failure is that the 1.14.6 image is not yet available (which is a common occurrence for new go versions).
> 
> I'll fix this up and rebuild the job later today, as we also need kube-cross built for go1.13.14.

make sense :)

**Comment by BenTheElder** [comment]
in other prow + GCB jobs we have the extra log files included in $ARTIFACTS
so you can see all of them there.

**Comment by justaugustus** [comment]
Hmmm... will check it out later. Thanks!

**Pull request merged**
