### PR TITLE
Fix typo at announce.go

### PR DESCRIPTION
**Pull request by jongwooo**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Correct typo from 'annoucements' to 'announcements' at `announce.go`.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
Thanks
/ok-to-test

**Review by saschagrunert — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
