### PR TITLE
Simplify `OWNERS` and federate review obligations

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- Simplify OWNERS and federate review obligations

  This change seeks to federate reviews to more of the Release Manager
  Associates, while simplifying some of the aliases we use for reviews and
  approvals, based on the following:

  For top-level:

  - Remove `release-engineering-approvers` as reviewers

  For aliases that covered areas that no longer exist:

  - Remove alias

  For areas where reviewers == approvers:

  - Remove the reviewers alias
  - List `release-engineering-reviewers` as reviewers
  - Explicitly list any contributors who have been reviewing prior to joining
  any named teams e.g., Release Managers

- OWNERS: Add Verolop to `release-engineering-approvers` (ref: https://github.com/kubernetes/sig-release/issues/1713)

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @puerco @cpanato @saschagrunert @jeremyrickard 
cc: @kubernetes/release-engineering 

#### Special notes for your reviewer:

To add some commentary in non-commit-message form...

This PR is the aggregate of some discussions across:

- removing myself from certain review paths
- thinking about how we do reviews/approvals in this subproject and the wider project

A few observations:

- leads are in the critical path for too many reviews
- when reviewers == approvers, reviewers who are not approvers are not empowered to review at the level which they would need to prove themselves as eventual approvers

To fix this, we're attempting to adhere to https://go.k8s.io/owners#maintaining-owners-files:

> Good examples of OWNERS usage:
>
> - team aliases are used that correspond to sigs
> - there are more `reviewers` than `approvers`
> - the `approvers` are not in the `reviewers` section
> - OWNERS files that are regularly updated (at least once per release)

Namely:
> the `approvers` are not in the `reviewers` section

Somewhat related discussions can be found here:

- should reviewers become reviewers before they've done reviews: https://github.com/kubernetes/release/pull/2327#issuecomment-975976579
- should approvers be listed as reviewers: https://github.com/kubernetes/test-infra/pull/24328#discussion_r747707785

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Eventually, it would be nice to use a tool like @dims' https://github.com/dims/maintainers to programmatically make some of these decisions.

Example:
- https://kubernetes.slack.com/archives/C1TU9EB9S/p1637343746206800?thread_ts=1637343579.206700&cid=C1TU9EB9S
- https://pastebin.ubuntu.com/p/45GRMp4Dxb/plain/
- https://github.com/dims/kubernetes/commit/5e586df3fb0586b77133e1e12f2c3afc54a8c545
- https://github.com/dims/maintainers/blob/4a3f206d1ba43053f520ba4579c1153b9618ca05/maintainers.go#L154-L161

**Comment by justaugustus** [comment]
p.s. for anyone passing by this PR that's interested in reviewing in a particular area, feel free to open a PR to discuss :)

**Review by saschagrunert — APPROVED** [review]
As already discussed in the leads sync:
/lgtm

**Review by cpanato — APPROVED** [review]
thanks! agree
/lgtm

**Comment by justaugustus** [comment]
Discussed in today's RelEng meeting:
/hold cancel

**Pull request merged**
