### PR TITLE
Use dateless boilerplate in generated files

### PR DESCRIPTION
**Pull request by hasheddan**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Updates generated license headers to use dateless boilerplate. Changes in this commit were
generated by running `make update-mocks`.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

#### Which issue(s) this PR fixes:

n/a

#### Special notes for your reviewer:

We should probably follow this up by running CI that makes sure that running generation does not create a diff.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by justaugustus — CHANGES_REQUESTED** [review]
@hasheddan -- Would suggest using boilerplate with the copyright date stripped on generated files. Here's the example from k/k: https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.generatego.txt

**Comment by hasheddan** [comment]
@justaugustus this should be ready to go now :+1:

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
