### PR TITLE
switch to python3, remove python2

### PR DESCRIPTION
**Pull request by hoegaarden**
ref: https://github.com/kubernetes/release/issues/932

I also took the liberty to introduce some light testing of our image.

/kind cleanup
/assign @tpepper

### CODE REVIEW

**Comment by hoegaarden** [comment]
I at least want to run mock staging / releasing with that image, to see if some python thing blows up.

**Comment by hoegaarden** [comment]
I ran mock stage & release with the changed image and the code from this PR. On a first sight everything looks good for those.

- successful stage: https://console.cloud.google.com/cloud-build/builds/95e97602-57ea-49db-a01c-65e43055ad0c?project=kubernetes-release-test
- successful release: https://console.cloud.google.com/cloud-build/builds/443e5fb5-5424-48de-bca6-517946592401?project=kubernetes-release-test

/assign @justaugustus

**Comment by justaugustus** [comment]
Let's ship it!
/lgtm
/approve

**Comment by tpepper** [comment]
I kind of would have been inclined to go conservative on this and wait until Dec. 9 and the 1.17 release have been successful.  We don't have the best of test coverage on this stuff...

**Comment by hoegaarden** [comment]
> We don't have the best of test coverage on this stuff...

Yeah ... we pretty much have none.

> I kind of would have been inclined to go conservative on this [...]

Note that this only created and pushed the images `gcr.io/k8s-staging-release-test/k8s-cloud-builder:{v20191123-v0.1.3-183-g8455af2,latest}`. In the release process we use the image `gcr.io/kubernetes-release-test/k8s-cloud-builder:latest`. So the former needs to be promoted to the later, which has not happened yet.

I am not entirely sure about the current promotion process, who, when, why and how pushes images to `gcr.io/kubernetes-release-test/`. I guess @justaugustus, @alexeldeib and others might know more. I don't think there is any automation (image-promoter) or even process in place yet, but that's on the list (https://github.com/kubernetes/release/issues/911). Right now, I presume, it might just be manual thing (`docker tag`, `docker push`) for folks who hold the right keys.

**Pull request merged**
