### PR TITLE
anago: push git branch verbose

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind regression

#### What this PR does / why we need it:
For debugging purposes, we now logecho -v (verbose) to retrieve the
reason why the branch push failed.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
We may revert that change later on again.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@justaugustus which invocations did you do to trigger the test-failure?

**Comment by justaugustus** [comment]
`krel gcbmgr --stage --type official --branch release-1.18`

**Comment by saschagrunert** [comment]
> `krel gcbmgr --stage --type official --branch release-1.18`

Thanks, I'll trigger a new run after that PR got merged.

**Comment by saschagrunert** [comment]
Ah @justaugustus this still needs approval :)

**Comment by justaugustus** [comment]
Ooop! I accidentally removed the `approved` label when pulling the `blocked-paths` label.
Should merge in a bit now.

**Pull request merged**
