### PR TITLE
Update cloud.google.com/go dependency to cloud.google.com/go/storage

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Update golang based dependencies to their latest version, which includes:
- cloud.google.com/go: removed
- cloud.google.com/go/storage: v1.6.0

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
- Switch from cloud.google.com/go to cloud.google.com/go/storage (v1.6.0)
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Needs https://github.com/GoogleCloudPlatform/testgrid/pull/90 (ref https://kubernetes.slack.com/archives/C5NV3MT97/p1581076477055900)

**Comment by justaugustus** [comment]
@saschagrunert -- I did some golang updates in https://github.com/kubernetes/release/pull/1142 to unblock the non-testgrid related ones.

When you have a chance, can you rebase this?

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch to resolve the conflicts.

**Comment by saschagrunert** [comment]
I'm closing this and will revisit in some time.

**Pull request closed without merging**
