### PR TITLE
Remove global LANG setting.  Too disruptive at this scope.

### PR DESCRIPTION
**Pull request by david-mcmahon**
cc @cblecker

### CODE REVIEW

**Comment by david-mcmahon** [comment]
Which "`perl`" commands are being affected here?

**Comment by ixdy** [comment]
I think the sha1/md5 commands.

**Comment by david-mcmahon** [comment]
How so? Those are not affected by $LANG.
```
$ md5sum /tmp/rotatelog.6636 
37c54f0f94fc17b924156cbb41c406b5  /tmp/rotatelog.6636
$ LANG=C md5sum /tmp/rotatelog.6636 
37c54f0f94fc17b924156cbb41c406b5  /tmp/rotatelog.6636
```

Either way this is causing issues.  If LANG=C is appropriate for some commands, they can be scoped individually.

**Comment by cblecker** [comment]
From the original PR:
> push-build.sh spits out a bunch of warnings that the perl commands fall back to POSIX:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46487/pull-kubernetes-e2e-gce-etcd3/33195/?log#log

What is failing now as a result of this?

**Comment by david-mcmahon** [comment]
This pretty [$HR value](https://github.com/kubernetes/release/blob/master/lib/common.sh#L60) gets borked.  If we want to scope this to push-build.sh and anything downstream (sourced), we could add it there or be more selective about which perl invocations are spewing the warnings.

**Comment by cblecker** [comment]
Gotcha. Yeah, we could set it in push build, or we could set it in the common::sha function (line 624 of common.sh) as a local var as that's my guess at the one that's actually spitting the error (based on https://linux.die.net/man/1/shasum which notes that it's implemented using Perl).

**Comment by ixdy** [comment]
`common::sha` SGTM

**Comment by david-mcmahon** [comment]
PTAL

**Comment by cblecker** [comment]
Works for me

**Pull request merged**
