### PR TITLE
New editor to remove k8s.io/kubectl/pkg/cmd/util/editor dependency

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:

This PR strips out the `k8s.io/kubectl/pkg/cmd/util/editor` dependency from krel/release-notes. The main code is divided in two commits:

The firs commit adds a new package `k8s.io/release/pkg/editor` which is a stripped down fork of the kubectl version with the k/k dependencies removed or replaced (eg klog calls have been replaced to equivalent calls to sirupsen/logrus which we use already). It also modifies the `krel release-note` subcommand to use the new module.

The new package includes the same tests included in the kubectl version, with slight changes to work with our fork

The second commit includes the modified go.mod and go.sum files (with dependencies updated) and are split expecting a need to rebase after #1598 merges.

#### Which issue(s) this PR fixes:
Ref: kubernetes-sigs/kubetest2#61

#### Special notes for your reviewer:

_Bonus:_ I added a  bug fix por a permissions problem I found while testing in the release package where `TestCopyBinaries()` created an inaccesible directory.

#### Does this PR introduce a user-facing change?
```release-note
- New package `k8s.io/release/pkg/editor` gets rid of the dependency to the editor package in kubectl.
```
/cc @saschagrunert @JamesLaverack @justaugustus

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/hold
I expect that we want to wait for https://github.com/kubernetes/release/pull/1598 first.

**Comment by puerco** [comment]
They are independent of each other and will cause the other to need to rebase. We can merge this one and I'll rebase 1598

**Pull request merged**
