### PR TITLE
deps: Add dependency versions check via zeitgeist and update repo-infra to v0.1.1

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

- dependencies.yaml: Fixup regexes for repo-infra and golangci-lint
- deps: Update repo-infra to v0.1.1
- compile-release-tools: Allow external tools to be compiled
- deps: Add dependency versions check via zeitgeist
- Makefile: Reorder verify targets to allow faster targets to run first

#### Does this PR introduce a user-facing change?

```release-note
- deps: Update repo-infra to v0.1.1
- deps: Add dependency versions check via zeitgeist
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
CI seems unhappy:
```
Running error: buildir: failed to load package : could not load export data: no export data for \"k8s.io/api/auditregistration/v1alpha1\"
```

**Comment by justaugustus** [comment]
/assign @hasheddan @saschagrunert 
cc: @kubernetes/release-engineering

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
