### PR TITLE
release-notes: Allow configuration of github org / repo

### PR DESCRIPTION
**Pull request by jsafrane**
`release-notes` is useful for other Kubernetes repos too.

Tested with `kubernetes-csi/external-attacher`: 

`release-notes --start-sha=b7dadac426820e168e90780a7797f1ebb62a79a8 --end-sha=70a1411e167a4c25a0650d827b1671ad676bfa73 --github-org=kubernetes-csi --github-repo=external-attacher --branch=master
`

### CODE REVIEW

**Comment by marpaia** [comment]
Nice diff! Really neat re-usage of the functionality.

/lgtm
/approve

**Comment by jeefy** [comment]
omg yes! This is awesome!

@jsafrane If you wouldn't mind taking a peek at https://github.com/kubernetes/enhancements/pull/928 it'd be appreciated. It's where I'd like to take things with release notes and I'd love to discuss if it could apply to other repos.

**Comment by justaugustus** [comment]
Awesome improvement, @jsafrane!
/lgtm
/approve

**Pull request merged**
