### PR TITLE
Download the kubeadm for the right arch

### PR DESCRIPTION
**Pull request by luxas**
Fixes so the kubeadm package becomes multiarch

@mikedanese @errordeveloper

### CODE REVIEW

**Comment by luxas** [comment]
Verified that this isn't a regression, kubeadm is uploaded to the new path as well

**Comment by luxas** [comment]
@mikedanese I think this is the last piece we need before our debs can be released to stable
I'll push arm and arm64 `kubeadm` binaries tomorrow

**Comment by mikedanese** [comment]
I'd really like for this to pull from gs://kubernetes-release-dev but not sure if this is going to be possible to do by tomorrow.

**Comment by luxas** [comment]
For tomorrow I think we can go with this.
I'm gonna make sure arm and arm64 binaries are there tomorrow for you @mikedanese, so we can build the final kubeadm release

**Comment by luxas** [comment]
@mikedanese BTW, if you like and have time, you can try to minimize the delta between debs and rpms :)

**Pull request merged**
