### PR TITLE
pkg/cip: Use cenkalti/backoff/v4 to remove dep on k8s.io/apimachinery

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

https://github.com/kubernetes/release/pull/1767 pulled in a dependency on `k8s.io/apimachinery` (`pkg/util/wait`) for exponential backoffs in the image promotion logic.

A versioned staging repo dependency could cause issues for downstream dependents, so let's replace it with https://github.com/cenkalti/backoff.

/hold because this is panicking at the moment

#### Does this PR introduce a user-facing change?

```release-note
- pkg/cip: Use cenkalti/backoff/v4 to remove dep on k8s.io/apimachinery
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Ready!

/hold cancel
/assign @hasheddan @saschagrunert @cpanato

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
@saschagrunert -- Needs re-`/lgtm` (https://github.com/kubernetes/release/pull/1798 forced a rebase).

**Review by cpanato — APPROVED** [review]
nice
/lgtm

**Pull request merged**
