### PR TITLE
Update all repo dependencies

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

- go.mod: Update to go1.15 directives
- deps: Move tools to its own module
- deps: Update all dependencies

|                 MODULE                  |              VERSION               |            NEW VERSION             | DIRECT | VALID TIMESTAMPS |
|-----------------------------------------|------------------------------------|------------------------------------|--------|------------------|
| cloud.google.com/go                     | v0.44.3                            | v0.66.0                            | true   | true             |
| github.com/GoogleCloudPlatform/testgrid | v0.0.10                            | v0.0.22                            | true   | true             |
| github.com/bazelbuild/rules_go          | v0.23.3                            | v0.24.2                            | true   | true             |
| github.com/golang/protobuf              | v1.3.2                             | v1.4.2                             | true   | true             |
| github.com/google/uuid                  | v1.1.1                             | v1.1.2                             | true   | true             |
| github.com/sendgrid/rest                | v2.6.0+incompatible                | v2.6.1+incompatible                | true   | true             |
| github.com/sendgrid/sendgrid-go         | v3.6.0+incompatible                | v3.6.3+incompatible                | true   | true             |
| github.com/yuin/goldmark                | v1.1.32                            | v1.2.1                             | true   | true             |
| golang.org/x/net                        | v0.0.0-20200602114024-627f9648deb9 | v0.0.0-20200904194848-62affa334b73 | true   | true             |
| golang.org/x/oauth2                     | v0.0.0-20200107190931-bf48bf16ab8d | v0.0.0-20200902213428-5d25da1a8d43 | true   | true             |
| google.golang.org/api                   | v0.21.0                            | v0.32.0                            | true   | true             |
| gopkg.in/yaml.v2                        | v2.2.8                             | v2.3.0                             | true   | true             |
| k8s.io/apimachinery                     | v0.18.6                            | v0.19.2                            | true   | true             |
| k8s.io/kubectl                          | v0.18.6                            | v0.19.2                            | true   | true             |
| k8s.io/utils                            | v0.0.0-20200324210504-a9aa75ae1b89 | v0.0.0-20200912215256-4140de9c8800 | true   | true             |

/assign @hasheddan @saschagrunert 
cc: @kubernetes/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
- go.mod: Update to go1.15 directives
- deps: Move tools to its own module
- deps: Update all dependencies
```

### CODE REVIEW

**Comment by puerco** [comment]
Looks good to me (but too scared to pull the trigger), great update @justaugustus thanks!

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
