### PR TITLE
kube-cross: Build v1.15.0-rc.1-1 image

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency
/priority important-soon

#### What this PR does / why we need it:

Build kube-cross v1.15.0-rc.1-1 image

Tracking issue: https://github.com/kubernetes/release/issues/1421.
ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1595620045212200?thread_ts=1595270953.060000&cid=C2C40FMNF

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @tpepper @saschagrunert @hasheddan @cpanato @dims @liggitt 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/hold for the image to actually be available

#### Does this PR introduce a user-facing change?

```release-note
kube-cross: Build v1.15.0-rc.1-1 image
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
if we're still using the dockerhub golang image rc1 doesn't appear to exist yet

**Comment by justaugustus** [comment]
> if we're still using the dockerhub golang image rc1 doesn't appear to exist yet

> /hold for the image to actually be available

Yep. :sweat_smile:
I might be looking into getting our own golang images rolling after we land go1.15.0.

**Comment by BenTheElder** [comment]
rc1 is live  https://hub.docker.com/_/golang?tab=tags&page=1&ordering=last_updated

**Comment by BenTheElder** [comment]
/hold
except like, only a couple architectures (??)

**Pull request merged**
