### PR TITLE
[GO] build Go 1.18.1 and 1.17.9 images

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Build Go 1.18.1 and 1.17.9 images.

/assign @saschagrunert @Verolop @xmudrii  @palnabarun @puerco @justaugustus 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

xref #2499 

#### Does this PR introduce a user-facing change?

```release-note
build Go 1.18.1 and 1.17.9 images
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
`RESOURCE_EXHAUSTED`
/retest

**Comment by palnabarun** [comment]
/lgtm

All jobs are green! 🎉

**Comment by cpanato** [comment]
/unhold

i will watch the post submits and when those are green will run the promotion

**Pull request merged**
