### PR TITLE
Update golangci-lint and config

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Adds support for go 1.20.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by saschagrunert** [comment]
Now this should work :grin:

**Pull request merged**
