### PR TITLE
Migrate promotion CLI tools to k/release

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

As part of the CIP repo improvements in https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/266, we're going to be moving CLI tools to k/release to allow some opportunities to dedupe common libraries and further integrate these tools into the k/k release process.

- Migrate promotion CLI tools to k/release
- Update promotion imports to use k/release/pkg/*
- Use klog v2 for promo tools
- generated: Run go mod tidy
- pkg/{api,filepromoter,promobot}: Lint fixes

#### Special notes for your reviewer:

Notably, this does not include the container image promoter tool (`cip.go`).
That's currently entangled with bazel and will take some time to decompose.

Additionally, this is meant to be a migration of tools, so this PR includes very minimal code cleanups (only those strictly required to allow tests to pass).

#### Does this PR introduce a user-facing change?

```release-note
- Migrate promotion CLI tools to k/release
  The following tools have been added to the repo:
  - `cip-mm`
  - `promobot-files`
  - `promobot-generate-manifest`
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @listx @justinsb @saschagrunert @hasheddan 
cc: @kubernetes/release-engineering

**Review by hasheddan — APPROVED** [review]
/lgtm

:tada:

**Comment by hasheddan** [comment]
/hold

for image promoter folks to take a look (feel free to cancel if not needed)

**Review by markyjackson-taulia — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
> for image promoter folks to take a look (feel free to cancel if not needed)

@hasheddan -- I discussed with Linus this week, but thanks for being cautious!
/hold cancel

**Comment by justaugustus** [comment]
CIP repo follow-up here: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/273

**Comment by listx** [comment]
Thanks @justaugustus !

**Pull request merged**
