### PR TITLE
Revert "kube-cross: update protobuf version"

### PR DESCRIPTION
**Pull request by dims**
This reverts commit 4469d9f439f357d462e51880ff55510b724fe1f7.

Slack discussion and context:
https://kubernetes.slack.com/archives/CJH2GBF7Y/p1691455658790099?thread_ts=1691147246.081229&cid=CJH2GBF7Y

Started by an observation from @jeremyrickard:
https://kubernetes.slack.com/archives/CJH2GBF7Y/p1691448767978169?thread_ts=1691147246.081229&cid=CJH2GBF7Y

```
+++ [0807 21:34:09] Running build command...
Generating protobuf requires protoc 3.19.4.
Run hack/install-protoc.sh or download and install the
platform-appropriate Protobuf package for your OS from
https://github.com/protocolbuffers/protobuf/releases
```

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by liggitt** [comment]
We've got built kube-cross images for release branches already with the updated protoc version now. If we revert, we'll either have to rebuild those or change k/k expected protoc versions now and then change them back later.

**Comment by dims** [comment]
sounds like a plan. thanks @liggitt

**Pull request closed without merging**
