### PR TITLE
Refactor unsued releaselib bash into push-build.sh

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
All functions which are not used by `anago` are now directly part of
`push-build.sh`. This allows us to get a better distinction between both
scripts when it comes to further refactorings.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/hold
would like to verify if anago still works as intended.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/lgtm
/approve

Feel free to lift the hold when you're ready to.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
#### Manual Testing

##### Stage
```
> export TOOL_ORG=saschagrunert && \
  export TOOL_BRANCH=push-build-split && \
  go run ./cmd/krel gcbmgr --stage --branch master --type alpha
```

- :heavy_check_mark: Logs looking good: https://console.cloud.google.com/cloud-build/builds/00d36918-4c9f-4687-b5e0-bd42b612ced9?project=kubernetes-release-test

##### Release
```
> export TOOL_ORG=saschagrunert && \
  export TOOL_BRANCH=push-build-split && \
  go run ./cmd/krel gcbmgr --release --branch master --type alpha --build-version v1.20.0-alpha.1.366+c9c24b46c35fea
```

- :hourglass: : Waiting for logs: https://cloudbuild.googleapis.com/v1/projects/kubernetes-release-test/builds/47263ea6-5e46-4e41-8c98-8b4bc39a8f19

**Pull request merged**
