### PR TITLE
Fix cherrypick guide link.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
/cc @david-mcmahon

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Fixes: https://groups.google.com/forum/#!topic/kubernetes-dev/q6VQMp-9Qa8

**Comment by david-mcmahon** [comment]
Thanks.  I had this going in another PR as well, but you beat me to it.

**Comment by xiangpengzhao** [comment]
@david-mcmahon ah, sorry for not noticing your PR :)

**Comment by david-mcmahon** [comment]
@xiangpengzhao no worries, it wasn't quite obvious anyway as it was part of a series of other fixes as well.  Thanks for being so proactive on this repo!

**Pull request merged**
