### PR TITLE
Rename release-notes --github-org/repo flags

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind api-change

#### What this PR does / why we need it:
We should drop the `github` prefix from those flags to allow a less
verbose usage.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
#### Does this PR introduce a user-facing change?

```release-note
- Changed `release-notes` `--github-[org,repo]` flags to be just `--org` and `--repo`
```

### CODE REVIEW

**Comment by puerco** [comment]
A couple of months back, @justaugustus suggested this change to me. At the time I was working on krel and I thought he meant to change the flag in `krel release-notes` and not in the `release-notes` command, so I shortened the old flag in `krel release-notes` to --org. 

I think we should change the --org flag in krel release-notes (currently the user's org) because it is not consistent with --org in other parts of the codebase (meaning the kubernetes organization). What would a good replacement be?

Maybe `--user-org`?

**Comment by justaugustus** [comment]
`--org` is meant to "whatever namespace I'm doing the operation on".
Usually, that's `kubernetes`, but it doesn't need to be (hence the flag).

What would be the purpose of `--user-org`?

**Comment by puerco** [comment]
`krel release-notes` takes the user's Github organization to create the release notes PR and the website PR  (it's where his forks of /sig-release and ksigs/release-notes are). I think it is confusing because these are meant to push the changes and not to operate on, WDYT?

**Comment by saschagrunert** [comment]
I see, what about accepting a slug and call the flag `--fork [org/repo]`?

**Comment by puerco** [comment]
Sounds good to me. A single --fork would allow us to get rid of three flags, resulting in a much cleaner cli IMHO. These would go away:
`--org` `--draft-repo` and `--website-repo`

**Comment by saschagrunert** [comment]
> Sounds good to me. A single --fork would allow us to get rid of three flags, resulting in a much cleaner cli IMHO. These would go away:
> `--org` `--draft-repo` and `--website-repo`

Yes, I agree! :) One if the reasons to keep those input values separated could be when they’re used by scripts, but this is not the case for `krel release-notes`. 👍

**Pull request merged**
