### PR TITLE
Copy stdout and stderr in parallel to sync output

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The previous behavior could cause to dead-lock the command execution if
a process is waiting for stdout but only produces output on stderr. To
avoid this, we now start the copy in parallel and sync-up the operation
by waiting on the `done` channel.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Fixed bug where a `command` execution could dead-lock when only producing stderr output. Both streams are now in sync.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/hold cancel

This can be reviewed :)

**Comment by puerco** [comment]
:rocket:  Nice!

/lgtm

**Pull request merged**
