### PR TITLE
dependencies.yaml: Update zeitgeist to v0.3.0

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup
/area dependency

#### What this PR does / why we need it:

We're on an older version of zeitgeist and that dep has seen a few changes since we last pulled it in.

/assign @cpanato @saschagrunert @xmudrii 

#### Does this PR introduce a user-facing change?

```release-note
dependencies.yaml: Update zeitgeist to v0.3.0
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by xmudrii** [comment]
/retest
I don't see any error, strange.

**Comment by xmudrii** [comment]
I've tried running `make verify` locally on this branch and it works. I'm probably missing something obvious, but let's try to retest again. :shrug: 
/retest

**Comment by justaugustus** [comment]
@xmudrii -- I _think_ it's failing silently because the $PATH in CI is not being interpreted properly.

I can take a look later if it fails again.

**Comment by justaugustus** [comment]
This is passing now, but let's:

/hold for the next zeitgeist release (after https://github.com/kubernetes-sigs/zeitgeist/pull/31 merges)

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
