### PR TITLE
build Go 1.19 images

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- golang: build 1.19 images

#### Which issue(s) this PR fixes:

Part of #2575 

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
- golang: build 1.19 images
```

/assign @saschagrunert @palnabarun @Verolop @ameukam @justaugustus 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by cpanato** [comment]
for go-runner

```
Step #1: error: failed to solve: golang:1.19-bullseye: no match for platform in manifest sha256:072564420b4ecdb4fb7092b8ac8480912aaf14202bc5c964d867246d4047c755: not found
``
`

```
$ docker manifest inspect golang:1.19-bullseye | grep -e '"architecture"' -e '"os"'
            "architecture": "amd64",
            "os": "linux"
            "architecture": "arm64",
            "os": "linux",
            "architecture": "386",
            "os": "linux"
            "architecture": "s390x",
            "os": "linux"

```
looks like we need to wait a bit more

**Comment by cpanato** [comment]
need more

```
$ docker manifest inspect golang:1.19-bullseye | grep -e '"architecture"' -e '"os"'
            "architecture": "amd64",
            "os": "linux"
            "architecture": "arm64",
            "os": "linux",
            "architecture": "386",
            "os": "linux"
            "architecture": "ppc64le",
            "os": "linux"
            "architecture": "s390x",
            "os": "linux"
```

**Comment by dims** [comment]
We now have all the images needed:
https://hub.docker.com/_/golang?tab=tags&page=1&name=1.19

```
$ docker manifest inspect golang:1.19 | grep -e '"architecture"' -e '"os"'
            "architecture": "amd64",
            "os": "linux"
            "architecture": "arm",
            "os": "linux",
            "architecture": "arm64",
            "os": "linux",
            "architecture": "386",
            "os": "linux"
            "architecture": "mips64le",
            "os": "linux"
            "architecture": "ppc64le",
            "os": "linux"
            "architecture": "s390x",
            "os": "linux"
            "architecture": "amd64",
            "os": "windows",
            "architecture": "amd64",
            "os": "windows",
```

**Comment by dims** [comment]
/hold

probably need to wait for the CI jobs to be green :)

**Comment by dims** [comment]
`pull-release-image-go-runner` failed twice. will wait for @palnabarun or @cpanato or @ameukam :)

**Comment by puerco** [comment]
I retriggered the job and it worked, I'll try again to check.
/test pull-release-image-go-runner

**Comment by puerco** [comment]
I'm trying to investigate why it's flaking I'm going to merge this one to get signal from the 1.19 builder images.
/hold cancel

**Pull request merged**
