### PR TITLE
dependencies: update several dependecies

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Update dependencies, January 2021 cycle 😄 

- Update `cloud.google.com/go` dependency to [v0.75.0](https://github.com/googleapis/google-cloud-go/tree/v0.75.0) which is the latest available and has the [following changes](https://github.com/googleapis/google-cloud-go/releases/tag/v0.75.0)
- Update `github.com/GoogleCloudPlatform/testgrid` dependency to [v0.0.38](https://github.com/GoogleCloudPlatform/testgrid/tree/v0.0.38) which is the latest available and has the [following changes](https://github.com/GoogleCloudPlatform/testgrid/releases/tag/v0.0.38)
- Update `github.com/google/go-containerregistry` dependency to [v0.3.0](https://github.com/google/go-containerregistry/tree/v0.3.0) which is the latest available and has the [following changes](https://github.com/google/go-containerregistry/releases/tag/v0.3.0)
- Update `github.com/google/uuid` dependency to [v1.1.4](https://github.com/google/uuid/tree/v1.1.4) which is the latest available and has the [following changes](https://github.com/google/uuid/releases/tag/v1.1.4)
- Update `github.com/mitchellh/mapstructure` dependency to [v1.4.1](https://github.com/mitchellh/mapstructure/tree/v1.4.1) which is the latest available and has the [following changes](https://github.com/mitchellh/mapstructure/releases/tag/v1.4.1)
- Update `github.com/moby/term` dependency to `v0.0.0-20201216013528-df9cb8a40635`
- Update `github.com/shirou/gopsutil/v3` dependency to [v3.20.12](https://github.com/shirou/gopsutil/tree/v3.20.12) which is the latest available and has the [following changes](https://github.com/shirou/gopsutil/releases/tag/v3.20.12)
- Update `github.com/stretchr/testify` dependency to [v1.7.0](https://github.com/stretchr/testify/tree/v1.7.0) which is the latest available and has the [following changes](https://github.com/stretchr/testify/releases/tag/v1.7.0)
- Update `github.com/yuin/goldmark` dependency to [v1.3.1](https://github.com/yuin/goldmark/tree/v1.3.1) which is the latest available and has the [following changes](https://github.com/yuin/goldmark/releases/tag/v1.3.1)
- Update `golang.org/x/net` dependency to `v0.0.0-20201224014010-6772e930b67b`
- Update `golang.org/x/oauth2` dependency to `v0.0.0-20210112200429-01de73cf58bd`
- Update `google.golang.org/genproto` dependency to `v0.0.0-20210111234610-22ae2b108f89`
- Update `k8s.io/utils` dependency to `v0.0.0-20210111153108-fddb29f9d009`

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
- Update `cloud.google.com/go` dependency to `v0.75.0`
- Update `github.com/GoogleCloudPlatform/testgrid` dependency to `v0.0.38`
- Update `github.com/google/go-containerregistry` dependency to `v0.3.0`
- Update `github.com/google/uuid` dependency to `v1.1.4`
- Update `github.com/mitchellh/mapstructure` dependency to `v1.4.1`
- Update `github.com/moby/term` dependency to `v0.0.0-20201216013528-df9cb8a40635`
- Update `github.com/shirou/gopsutil/v3` dependency to `v3.20.12`
- Update `github.com/stretchr/testify` dependency to `v1.7.0`
- Update `github.com/yuin/goldmark` dependency to `v1.3.1`
- Update `golang.org/x/net` dependency to `v0.0.0-20201224014010-6772e930b67b`
- Update `golang.org/x/oauth2` dependency to `v0.0.0-20210112200429-01de73cf58bd`
- Update `google.golang.org/genproto` dependency to `v0.0.0-20210111234610-22ae2b108f89`
- Update `k8s.io/utils` dependency to `v0.0.0-20210111153108-fddb29f9d009`
```

/hold release after the patch releases are out 
/assign @hasheddan @saschagrunert

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by puerco** [comment]
/hold cancel
Thanks @cpanato  :)

**Comment by cpanato** [comment]
/hold 

the patches are not out yet :)

**Comment by saschagrunert** [comment]
Unfortunately this now needs a rebase, sorry!

**Comment by cpanato** [comment]
no worries @saschagrunert

**Comment by cpanato** [comment]
@saschagrunert rebased. PTAL! thanks!

**Review by saschagrunert — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
