### PR TITLE
Fix go tests and check in vendor folder

### PR DESCRIPTION
**Pull request by alvaroaleman**
This fixes the go tests and checks in the vendor folder, so a simple `go test ./...` presubmit can be added.

First half towards fixing #697 

Please review 4b04b28ccef7aaeb290e6d17f1f33d56f683ec64 thoroughly, I have no actual understanding of the tests and if the current behaviour matches the expectations.

### CODE REVIEW

**Comment by marpaia** [comment]
Is there any reason to check in the vendor folder? This is kind of an anti-pattern now with Go modules.

**Comment by alvaroaleman** [comment]
> Is there any reason to check in the vendor folder?

The reason was that it allows to add a simple `go test ./...` presubmit.

> This is kind of an anti-pattern now with Go modules.

Is it? (That's a genuine question). I imagine not checking it in to increase the duration of CI jobs and to introduce flakyness to them

**Comment by jeefy** [comment]
This is debatable. If it were later in the year I'd say making it adhere to gomods was a requirement. We're in a sort of transition period.

@alvaroaleman If you have some cycles this week to try and make it gomod-friendly I'd opt for that route. Otherwise I'd lgtm it and create an issue to track converting over to gomods so it doesn't get lost.

**Comment by alvaroaleman** [comment]
> @alvaroaleman If you have some cycles this week to try and make it gomod-friendly I'd opt for that route. Otherwise I'd lgtm it and create an issue to track converting over to gomods so it doesn't get lost.

I looked a little into this and adding the `go.mod`/`go.sum` files per se is pretty trivial. However it is required to import `go-github` as `github.com/google/go-github/v21` as it has a `go.mod` by itself and uses the `v21` suffix in its module name there. This in turn breaks Bazel:

```
$ bazel run //cmd/release-notes:release-notes
ERROR: /tmp/release/cmd/release-notes/BUILD.bazel:3:1: no such package '@com_github_google_go_github//v21/github'
```

I _think_ this is because `gazelle` has no releases version yet that supports go mods, albeit a patch for it being in `master`: https://github.com/bazelbuild/bazel-gazelle/commit/e051b0128d43288c89001feb83d2f4aeef41cfec

I am neither an expert in go modules nor in bazel so its entirely possible I missed something here, you can view the additional changes I did for go mods here: 
https://github.com/alvaroaleman/release/compare/fix-tests...alvaroaleman:gomods-demo?expand=1

I'd personally vote for merging this PR as-is until go mods work properly with bazel

**Comment by jeefy** [comment]
Thanks for looking into it! Given that, I agree. 

/lgtm

**Comment by marpaia** [comment]
I can't speak to the version checking test failure, but I agree that sticking with glide for now seems reasonable :+1:

**Pull request merged**
