### PR TITLE
xenial-kubelet: don't install /etc/default/kubelet

### PR DESCRIPTION
**Pull request by neolit123**
fixes https://github.com/kubernetes/release/issues/654

https://github.com/kubernetes/release/issues/654#issuecomment-468454123
> It is true that debian marks files under /etc as conf files, but whether to overwrite or not if both files changed is [determined](https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html#automatic-handling-of-configuration-files-by-dpkg) by an interactive prompt to the user by default. This will of course fail if updating non-interactively via scripts unless you supply your preferred version using `-y -o Dpkg::Options::="--force-confnew"`.

> So it's better to not package the `/etc/default/kubelet` at all for debian

cc @chuckha @mauilion @steven-sheehy 

/assign @timothysc

### CODE REVIEW

**Comment by ncdc** [comment]
FYI @rdodev @frapposelli @figo @akutz

**Comment by neolit123** [comment]
> Do you want to remove debian/xenial/kubelet/lib/default/kubelet Doesn't look like its used anywhere else

:+1:  forgot about the actual file. updated.
.

**Pull request merged**
