### PR TITLE
Update URL for release-notes-draft.md.

### PR DESCRIPTION
**Pull request by enisoc**
These files have moved from kubernetes/features to kubernetes/sig-release.

https://github.com/kubernetes/sig-release/pull/46
https://github.com/kubernetes/features/pull/529

### CODE REVIEW

**Comment by david-mcmahon** [comment]
/lgtm
Thanks.  I saw this happening.  Is it done yet?

**Comment by enisoc** [comment]
The new files are there; we copied previous releases over, and that's where we plan to put things for 1.10+. The old files haven't been removed quite yet, but it should be safe to start looking at the new location.

**Pull request merged**
