### PR TITLE
Switched from N1 to E2 machine

### PR DESCRIPTION
**Pull request by sarab97**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Replace existing N1 machine with better E2 machine

#### Which issue(s) this PR fixes:
Reference https://github.com/kubernetes/k8s.io/issues/5059

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by sarab97** [comment]
This is weird. There was no code change for this test to fail.

**Comment by cpanato** [comment]
Thanks for your PR

Can you add the specs difference and the price as well in the PR description?

**Comment by sarab97** [comment]
> Thanks for your PR
> 
> Can you add the specs difference and the price as well in the PR description?

@cpanato The referenced issue list the details.
The pricing isnt much different. But with E2 being more efficient and overall taking less time. The cost can be reduced.
https://cloud.google.com/blog/products/compute/google-compute-engine-gets-new-e2-vm-machine-types

**Comment by cpanato** [comment]
@sarab97 thank you!
i will check why the test is failing it is not related to this change

**Comment by cpanato** [comment]
this fixes https://github.com/kubernetes/release/pull/2990
as soon that gets merged please rebase

**Comment by sarab97** [comment]
@cpanato it worked. After rebase the test now passed.

**Review by cpanato — APPROVED** [review]
thank you
/approve
/lgtm

**Pull request merged**
