### PR TITLE
Remove find_green_build and all of its dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The questionable logic behind "finding a green build" for a release has
not been used by us since a long time. We usually pre-check the CI
before going to cut a release, which means that we can finally stick to
the ci/latest Jenkins build version on the corresponding branch.
#### Which issue(s) this PR fixes:

Replaces https://github.com/kubernetes/release/pull/1465
Incorporates with https://github.com/kubernetes/release/pull/1489
#### Special notes for your reviewer:
For more context see https://github.com/kubernetes/release/pull/1465#issuecomment-685156774
#### Does this PR introduce a user-facing change?

```release-note
- Removed `find_green_build` script and all of it's dependent logic
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Should close https://github.com/kubernetes/release/issues/873 since the job cache is not used any more now.

**Comment by tpepper** [comment]
I definitely like the diffstat on this one!

What do you think about rebasing-ish the other PR on this one, without any usage plumbing or intent to integrate with anago.  Ie: you've invested in writing a few hundred lines of feature in #1465.  If it that merges in repo we can maintain it hopefully.  And then optionally have it in pocket to use it if/when we're in a situation where we're just flummoxed by quality and want a quick read for "ok things are all haywire, where would we have to go if we wanted to build from something that did successfully navigate the test suite at least once".

We still have a need for some representation of this in testgrid.  For that we probably wouldn't use a search implementation versus a simple point test of "Is HEAD all green" or searching in a limited was "for current HEAD, has it ever been all green" and some other tests layered for "was that only green always in the past 24 hours", "was that only green always in the past 7 days" and "was that only green always in the past 14 days".  We do need these health metrics visible.  That limited search feeding layered summary across time spans might be able to leverage what you did in #1465.  Today we know such a test board would mostly generate a steady red signal as the timespan increases.  But once we get them steady green across a long timespan, the change to red is really important.  Trying to imagine if something that gives us more view through the haze of flakes.

**Comment by saschagrunert** [comment]
> What do you think about rebasing-ish the other PR on this one, without any usage plumbing or intent to integrate with anago. Ie: you've invested in writing a few hundred lines of feature in #1465. If it that merges in repo we can maintain it hopefully.

Sounds good! I can rebase on top of #1465, which basically drills down to not remove the golang parts in this PR. We still can get rid of many lines of untested bash. :fire:

**Comment by justaugustus** [comment]
/lgtm
/approve
/hold cancel

(Even more so as the removed code paths have blocked our k/repo-infra upgrades (via Testgrid) for months now: https://github.com/kubernetes/release/pull/1433)

**Pull request merged**
