### PR TITLE
k8s-ci-builder/releng-ci/kubepkg: add a REGISTRY substitution to allow registry selection

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
same work we did for kube-cross: https://github.com/kubernetes/release/pull/1943 we are applying for `k8s-ci-builder` and `releng-ci` and `kubepkg`

k/test-infra PR to update the jobs: TBC

/assign @justaugustus @saschagrunert @hasheddan 

tracking issue: https://github.com/kubernetes/release/issues/1850

/hold for the test-infra job update

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
`RESOURCE_EXHAUSTED: Quota exceeded for quota metric ` 

I think one thing we can do to avoid this, will check the image-builder service.

**Comment by cpanato** [comment]
checked the images and all have being built 

/hold cancel

**Review by justaugustus — APPROVED** [review]
/lgtm

**Pull request merged**
