### PR TITLE
Add gcb package

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The subcommand `krel gcbmgr` should move to a plain execution of `krel
stage/release` in the future. We still need the gcbmgr logic to achieve
that. To be able to use that logic directly in `krel stage/release`, we
must have it available as a package outside of the `cmd` package. This
is mainly what this commit achieves.

#### Which issue(s) this PR fixes:

Refers to #1673 
#### Special notes for your reviewer:
/hold 
for manual testing
#### Does this PR introduce a user-facing change?

```release-note
Added `gcb` package which is directly used by `krel gcbmgr`.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
#### Manual testing
- :hourglass_flowing_sand: Stage: https://console.cloud.google.com/cloud-build/builds/f036a775-1b06-4ac9-97c4-1413b368e299?project=648026197307
- :hourglass: Release

**Comment by saschagrunert** [comment]
Works
/unhold

**Review by cpanato — APPROVED** [review]
/lgtm
/hold for others to review

**Pull request merged**
