### PR TITLE
Fix notes_test build and apply small optimizations

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey :wave:, I had my first look into the release notes generation tool and saw that the notes tests do not build, which should be fixed now. Beside this, I packaged some small optimizations within certain commits, which I hope is fine too :)

### CODE REVIEW

**Comment by chrisz100** [comment]
Guess testing never hurt nobody and its just a small change. 

/ok-to-test

**Comment by saschagrunert** [comment]
I see that someone was faster than me and already fixed the test build. I rebased my PR on top of the latest master branch and kept my small optimizations.

**Pull request merged**
