### PR TITLE
Remove krel patch-announce

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind deprecation
/kind cleanup

#### What this PR does / why we need it:

As discussed in the Release Engineering Meeting, we now remove `krel
patch-announce` in favor of the more general `krel announce` subcommand.
Further refactorings will target the `pkg/patch` package, where some of
its components will be re-used by other tools.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/release/issues/1312

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
- Removed `krel patch-announce` in favor of the more general `krel announce` subcommand
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
> @saschagrunert -- We should support the replacement before deprecating this.
> /hold

Working on handbook updates here now: https://github.com/kubernetes/sig-release/pull/1098/files

**Comment by justaugustus** [comment]
@saschagrunert -- More explicitly, before we remove `patch-announce`, are we positive that `announce` has feature parity?

**Comment by saschagrunert** [comment]
> @saschagrunert -- More explicitly, before we remove `patch-announce`, are we positive that `announce` has feature parity?

Alright, those are the things `patch-announce` did:

1. Creating an announcement mail header
1. Building the release notes via `./relnotes`
1. Formatting the notes as HTML and merging it with the header
1. Sending the announcement

Whereas `announce` only does:

1. Downloading the announcement from the Google Cloud Bucket (previously built by anago)
1. Sending the announcement

Building the release notes again just for the mail should not be necessary, because `krel changelog` already does this job (anago expects a generated HTML after the notes have been built).

To streamline the overall process, I suggest to reuse parts of `pkg/patch` (not removed in this PR) for the golang based anago to create the announcement on the bucket.

It should be safe to remove `krel patch-announce` since it is not used in production, yet.

**Comment by justaugustus** [comment]
SGTM!
/hold cancel
/lgtm
/approve

**Pull request merged**
