### PR TITLE
go1.16rc1 mod tidy

### PR DESCRIPTION
**Pull request by wilsonehusin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Upgrading go1.16 changed the behavior of `go mod tidy`. I verified locally that even after this change, compiling with go1.15 still works.

#### Which issue(s) this PR fixes:

None, this is blocking #1884 though.

#### Special notes for your reviewer:

[Initial investigation from Marko](https://github.com/kubernetes/release/pull/1884#issuecomment-770464312)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by wilsonehusin** [comment]
I'm wondering if Prow built the [HEAD commit on master](b084389c2bf0b96d8054e23cd754f0d46452cda4) with 1.16 or not 🤔 

I personally would expect that Prow should, but I wonder if others think similarly?

**Comment by xmudrii** [comment]
The releng-ci image (which is used for running jobs) has been updated to Go 1.16 in #1882, which is the current HEAD. 

If this image is built by the CI, I’d expect that #1882 used the old image (based Go 1.15) to run jobs, and once the PR got merged, CI built the latest releng-ci image and then we started using that one (based on Go 1.16). As we didn’t had any PR in meanwhile, we didn’t notice that there’s a problem until #1884.

Also, consider that the verify job uses the latest tag of the image, so just pushing the image will make jobs to use the freshly-built image for all other PRs, even though the image hasn’t been tested.

It might be possible to fix this, but I’d consider this as expected, at least considering our current setup.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/hold
For other folks to make sure it’s okay to do it this way

cc @justaugustus @kubernetes/release-engineering

**Comment by justaugustus** [comment]
Thanks y'all!

/lgtm
/approve
/hold cancel

**Comment by houfangdong** [comment]
@wilsonehusin，[#1880](https://github.com/kubernetes/release/pull/1880#issuecomment-770483126)
I very much agree with your point of view, I also encountered the same problem.

**Pull request merged**
