### PR TITLE
Update CNI plugins to v1.2.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Update CNI plugins to the latest release.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Uploaded the artifacts to: https://console.cloud.google.com/storage/browser/k8s-artifacts-cni/release/v1.2.0

```
> kpromo gh --org containernetworking --repo plugins --bucket k8s-artifacts-cni --release-dir release --tags v1.2.0
```

#### Does this PR introduce a user-facing change?

```release-note
Updated CNI plugins to v1.2.0
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

thanks

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/115125

**Pull request merged**
