### PR TITLE
deps: update several dependencies

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update some dependencies:

- Update `github.com/go-git/go-git` dependency to [v5.1.0](https://github.com/go-git/go-git/tree/v5.1.0) which is the latest available and has the [following changes](https://github.com/go-git/go-git/releases/tag/v5.1.0)
- Update `github.com/sendgrid/rest` dependency to [v2.6.0](https://github.com/sendgrid/rest/tree/v2.6.0) which is the latest available and has the [following changes](https://github.com/sendgrid/rest/releases/tag/v2.6.0)
- Update `github.com/sendgrid/sendgrid-go` dependency to [v3.6.0](https://github.com/sendgrid/sendgrid-go/tree/v3.6.0) which is the latest available and has the [following changes](https://github.com/sendgrid/sendgrid-go/releases/tag/v3.6.0)
- Update `github.com/stretchr/testify` dependency to [v1.6.1](https://github.com/stretchr/testify/tree/v1.6.1) which is the latest available and has the [following changes](https://github.com/stretchr/testify/releases/tag/v1.6.1)
- Update `github.com/yuin/goldmark` dependency to [v1.1.32](https://github.com/yuin/goldmark/tree/v1.1.32) which is the latest available and has the [following changes](https://github.com/yuin/goldmark/releases/tag/v1.1.32)
- Update `github.com/bazelbuild/rules_go` dependency to [v0.23.3](https://github.com/bazelbuild/rules_go/tree/v0.23.3) which is the latest available and has the [following changes](https://github.com/bazelbuild/rules_go/releases/tag/v0.23.3)
- Update `golang.org/x/net` dependency to `v0.0.0-20200602114024-627f9648deb9`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
- Update `github.com/go-git/go-git` dependency to v5.1.0
- Update `github.com/sendgrid/rest` dependency to v2.6.0
- Update `github.com/sendgrid/sendgrid-go` dependency to v3.6.0
- Update `github.com/stretchr/testify` dependency to v1.6.1
- Update `github.com/yuin/goldmark` dependency to v1.1.32
- Update `github.com/bazelbuild/rules_go` dependency to v0.23.3
- Update `golang.org/x/net` dependency to v0.0.0-20200602114024-627f9648deb9
```

### CODE REVIEW

**Comment by cpanato** [comment]
@saschagrunert not ready yet :) it is in draft mode, i'm testing the other updates, it is a bit of pain to update 😅

**Comment by saschagrunert** [comment]
Okay cool, thank you for the update.

**Comment by cpanato** [comment]
@saschagrunert ready 😄 

/hold cancel

**Pull request merged**
