### PR TITLE
[go] Build go1.17.3 and go1.16.10 images

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:
Build image using go1.17.3 and go1.16.10

/assign @puerco @saschagrunert @Verolop @justaugustus 
/cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:
Part of #2304 

#### Does this PR introduce a user-facing change?

```release-note
[go] Build go1.17.3 and go1.16.10 images
```

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold

Remove the hold when ready

**Review by justaugustus — APPROVED** [review]
/hold cancel

**Pull request merged**
