### PR TITLE
Replace `gcloud container builds` with `gcloud builds`

### LINKED ISSUE #613: `gcloud container builds` is deprecated
From the command warning log and the [documents](https://cloud.google.com/sdk/gcloud/reference/container/builds/):

> This command is deprecated and will be removed on or after 2018-10-31. Please use [gcloud builds](
https://cloud.google.com/sdk/gcloud/reference/builds) instead.

### PR DESCRIPTION
**Pull request by idealhack**
Since it’s deprecated

Fixes #613

### CODE REVIEW

**Comment by tpepper** [comment]
Looks good to me, but will defer to the Googlers who've maintained the tool
/assign @david-mcmahon

**Comment by listx** [comment]
Hmm, I am not in OWNERS.

Can you approve for now @ixdy ?

**Comment by ixdy** [comment]
/approve
@listx we should get you added to OWNERS.

**Comment by idealhack** [comment]
Here is a new issue... since this PR was merged, we need to reconfigure the permission of the Google Cloud project, by changing all `gcloud.container.builds` to `gcloud.builds` I guess, otherwise, the new commands won't work. Sorry I didn't expect this. @listx

And just in case, do we have other parts needs to modify because of this change?

**Comment by listx** [comment]
@idealhack What commands are you running? Can you post some relevant logs of the errors you are seeing?

As for having to modify other parts, I am not sure. @djmm wdyt?

**Comment by idealhack** [comment]
@listx For example, while `glcoud container builds list` will show deprecated warnings, it runs fine. But `gcloud builds list` or `./gcbmgr list` will complain:

> ERROR: (gcloud.builds.list) User [idealhack] does not have permission to access project [kubernetes-release-test] (or it may not exist): Caller does not have required permission to use project unknown. Grant the caller the Owner or Editor role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=0 and then retry (propagation of new permission may take a few minutes).
> - '@type': type.googleapis.com/google.rpc.Help
>  links:
>  - description: Google developers console
>    url: https://console.developers.google.com
>- '@type': type.googleapis.com/google.rpc.Help
>  links:
>  - description: Google developer console IAM admin
>    url: https://console.developers.google.com/iam-admin/iam/project?project=0

**Comment by listx** [comment]
@AishSundar Hi Aish, can you reproduce the error idealhack is seeing from running `./gcbmgr list`?

**Comment by tpepper** [comment]
This happens for me also.  Eg:

With "containers" I get the deprecation warning:
```
[tpepper@tpepper-fedora-pet release]$ gcloud container builds list
WARNING: This command is deprecated and will be removed on or after 2018-10-31. Please
use `gcloud builds` instead.
WARNING: This command is deprecated and will be removed on or after 2018-10-31. Please
use `gcloud builds list` instead.
ERROR: (gcloud.container.builds.list) The required property [project] is not currently set.
You may set it for your current workspace by running:

  $ gcloud config set project VALUE

or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]
```

Without it I do not get the deprecation warning:
```
[tpepper@tpepper-fedora-pet release]$ gcloud builds list
ERROR: (gcloud.builds.list) The required property [project] is not currently set.
You may set it for your current workspace by running:

  $ gcloud config set project VALUE

or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]
```

**Comment by tpepper** [comment]
Ie: anybody in the world even with no project access can reproduce the problem.

**Comment by listx** [comment]
Sorry about the slow response; let's continue discussion in #616.

**Pull request merged**
