### PR TITLE
Update CNI plugins to v0.8.7

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

- packages: Update to CNI plugins v0.8.7
- images: Build debian-hyperkube-base:buster-v1.1.4
  - Update CNI plugins to v0.8.7

/assign @saschagrunert @cpanato @hasheddan 
cc: @kubernetes/release-engineering 

Continuation of https://github.com/kubernetes/kubernetes/pull/94367.

#### Does this PR introduce a user-facing change?

```release-note
- packages: Update to CNI plugins v0.8.7
- images: Build debian-hyperkube-base:buster-v1.1.4
  - Update CNI plugins to v0.8.7
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
The tests are failing:
```
--- FAIL: TestGetKubeadmDependencies (0.00s)
    --- FAIL: TestGetKubeadmDependencies/minimum_supported_kubernetes (0.00s)
        build_test.go:114: expected ["kubelet (>= 1.13.0)" "kubectl (>= 1.13.0)" "kubernetes-cni (>= 0.8.6)" "${misc:Depends}" "cri-tools (>= 1.13.0)"] but got ["kubelet (>= 1.13.0)" "kubectl (>= 1.13.0)" "kubernetes-cni (>= 0.8.7)" "${misc:Depends}" "cri-tools (>= 1.13.0)"]
```

**Comment by justaugustus** [comment]
> The tests are failing:

@saschagrunert -- should be fixed now

**Review by xmudrii — APPROVED** [review]
/lgtm
Looks good to me, but not sure do @saschagrunert and other assigned folks want to take another look
/hold

**Comment by justaugustus** [comment]
seems to be stuck on testing krel/cmd:
/test pull-release-test

**Review by hasheddan — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
