### PR TITLE
Add release notes JSON to artifacts

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This change allows us to create a release notes JSON as archived release artifact. Target is to re-use the new artifact directly from the release notes website.

#### Which issue(s) this PR fixes:

Refers to https://github.com/kubernetes/release/issues/1087
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Added release notes JSON as krel stage/release artifact
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
#### :heavy_check_mark: Stage
https://console.cloud.google.com/cloud-build/builds/99a54fc7-7590-4734-9c11-57df8e5c3488?project=kubernetes-release-test

**Comment by saschagrunert** [comment]
/hold

Let's wait for v1.20.0-rc.0 before merging this.

**Comment by saschagrunert** [comment]
/hold cancel

Might be better to merge sooner rather than later.

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
