### PR TITLE
Remove FLAGS_gcb from anago

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind api-change
/kind cleanup

#### What this PR does / why we need it:
We usually run anago only within GCB so we have no need for a dedicated
`--gcb` flag.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
This will break the usage of tools like `find_green_build` and `push-build` for local execution as well, becase we cannot distinguish any more if we're running locally.

#### Does this PR introduce a user-facing change?

```release-note
- Changed `anago` to always expect to be run inside GCB. This means local runs of `anago` are not possible any more.
```

### CODE REVIEW

**Comment by justaugustus** [comment]
For visibility: @kubernetes/release-managers

**Comment by saschagrunert** [comment]
> Can you provide more explicit detail about what would break in `find_green_build` and `push-build.sh`? I'm less concerned about `find_green_build`, but if "local" runs of `push-build.sh` break, it will break all of the `ci-kubernetes-build*` jobs.

- `find_green_build` is using `common:check_packages` which will now only work with Ubuntu.
- every script (`push-build.sh`, `find_green_build`, `prin`, `anago`) which is using `gitlib.sh` will now only work via GCB, because we do not pass the `FLAGS_gcb` any more.

The second one might be a bigger issue, I think I can solve it by reverting the change and setting the flag based on the script execution path…

**Comment by saschagrunert** [comment]
Testing…

<details>
 <summary>
    <code>$ TOOL_ORG=saschagrunert TOOL_BRANCH=flags-gcb krel gcbmgr --stage --type beta</code>
  </summary>

```
INFO Verifying repository state
INFO Repository is in clean state
INFO Found matching branch "flags-gcb"
INFO Found matching organization "saschagrunert" and repository "release" in remote: origin (git@github.com:saschagrunert/release)
INFO Verifying remote HEAD commit
INFO Got remote commit: 59a2fd57f1f13da1d8496860cb3b4352b7d2563d
INFO Verifying that remote commit is equal to the local one
INFO Repository is up-to-date
INFO Running gcbmgr with the following options: &{Stage:true Release:false Stream:false Branch:master ReleaseType:beta BuildVersion: GcpUser: LastJobs:5 Repo:0xc0003f9950 Version:0xc0003f9960}
INFO Build options: {  cloudbuild.yaml   kubernetes-release-test false false false   }
INFO Retrieving Kubernetes release version for ci/latest on branch master
INFO Retrieving Kubernetes build version from https://dl.k8s.io/ci/latest.txt...
INFO Retrieved Kubernetes version: v1.19.0-beta.0.348+7bd4c53b275f5c
INFO Trying to get the kube-cross version for master...
INFO Found the following kube-cross version: v1.13.9-5
INFO Listing GCB substitutions prior to build submission...
INFO BUILDVERSION: --buildversion=v1.19.0-beta.0.348+7bd4c53b275f5c
INFO NOMOCK_TAG:
INFO NOMOCK:
INFO TOOL_ORG: saschagrunert
INFO TOOL_BRANCH: flags-gcb
INFO TYPE: beta
INFO RELEASE_BRANCH: master
INFO BUILD_AT_HEAD:
INFO BUILD_POINT: v1.19.0-beta.0.348-7bd4c53b275f5c
INFO KUBE_CROSS_VERSION: v1.13.9-5
INFO TOOL_REPO: release
INFO GCP_USER_TAG: saschagrunert-at-gmail-com
INFO TYPE_TAG: beta
INFO Build directory: /home/sascha/go/src/k8s.io/release/gcb/stage
INFO Config directory: /home/sascha/go/src/k8s.io/release/gcb/stage
INFO cd-ing to build directory: /home/sascha/go/src/k8s.io/release/gcb/stage
ID                                    CREATE_TIME                DURATION  SOURCE  IMAGES  STATUS
25c09d7a-50f9-40e6-97f4-8044244141c4  2020-06-02T09:52:24+00:00  -         -       -       QUEUED
INFO: Refreshing access_token
Created [https://cloudbuild.googleapis.com/v1/projects/kubernetes-release-test/builds/25c09d7a-50f9-40e6-97f4-8044244141c4].
Logs are available at [https://console.cloud.google.com/cloud-build/builds/25c09d7a-50f9-40e6-97f4-8044244141c4?project=648026197307].
INFO: Display format: "
        table(
          id,
          createTime.date('%Y-%m-%dT%H:%M:%S%Oz', undefined='-'),
          duration(start=startTime,end=finishTime,precision=0,calendar=false,undefined="  -").slice(2:).join(""):label=DURATION,
          build_source(undefined="-"):label=SOURCE,
          build_images(undefined="-"):label=IMAGES,
          status
        )
      "
```
</details>

**Comment by justaugustus** [comment]
This should be good to merge now. Thanks @saschagrunert!
/lgtm
/approve
/hold cancel

**Comment by justaugustus** [comment]
@saschagrunert -- Given this was added:

```shell
export FLAGS_gcb=1
```

It merits an update to the release note. We're essentially faking GCB usage by unconditionally setting the flag, right?

**Comment by saschagrunert** [comment]
> @saschagrunert -- Given this was added:
> 
> ```shell
> export FLAGS_gcb=1
> ```
> 
> It merits an update to the release note. We're essentially faking GCB usage by unconditionally setting the flag, right?

Yep that’s right. I changed the release note, please take a look.

**Pull request merged**
