### PR TITLE
dependencies/cobra: update cobra to v0.0.7

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update cobra dependency to [v0.0.7](https://github.com/spf13/cobra/tree/v0.0.7) which is the latest available and has the [following changes](https://github.com/spf13/cobra/releases/tag/v0.0.7):

- Bug fix to restore previous exit behavior when a command is not runnable

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
dependencies/cobra: update cobra to v0.0.7
```

### CODE REVIEW

**Comment by hasheddan** [comment]
@cpanato I think failing test is related to this: https://github.com/spf13/cobra/issues/1056

**Comment by cpanato** [comment]
thanks @hasheddan 🤦‍♂

**Comment by cpanato** [comment]
@hasheddan I'm going to check that later, thanks!! :D

**Comment by cpanato** [comment]
@hasheddan @saschagrunert update the tests to reflect the change in the lib

**Pull request merged**
