### PR TITLE
Always switch to specified commit when tagging main branch

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

To avoid having unexpected merges to main/master landing between the commit in BuildVersion and the tag, `stage.TagRepository()` will now detach HEAD at the specified commit before tagging the repo. After creating the tag, it will return to the branch specified in the options.

#### Which issue(s) this PR fixes:
Followup to #1826 

#### Does this PR introduce a user-facing change?

```release-note
- To avoid having commits merged between BuildVersion and the tag, `stage.TagRepository()` will now check out the specified commit before tagging the main branch.
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

/hold for sascha reviews

**Comment by puerco** [comment]
Nope, I was rethinking this PR and came to the conclusion that this approach is wrong. Detaching the head to create the tags leaves us with the same situation as before. I gave it a test run and it is double-tagged again.

**Comment by puerco** [comment]
OK, I modified the behavior to only detach HEAD when running on the main branch. So, the tagging behavior works as follows:

* When running on a `release-M.mm` branch, we will create an empty commit and immediately create the tag at the empty commit.
* When running on main/master no empty commit gets created. `stage` will detach HEAD at the commit specified in BuildVersion, create the tag and checkout the branch again to reattach.

**Review by saschagrunert — APPROVED** [review]
/lgtm

Great to see that we catch this corner case now. :+1:

**Comment by justaugustus** [comment]
@puerco @saschagrunert -- where did we land w/ this?

**Comment by puerco** [comment]
This takes care of the edge case described by Sascha back when we [patched the tagging issue](https://github.com/kubernetes/release/pull/1826) in December. (TBH I thought we had already merged this).

Can we lift the hold?

**Review by saschagrunert — APPROVED** [review]
Yes
/hold cancel

**Pull request merged**
