### PR TITLE
dependencies: update several dependencies

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

update several dependencies:
- Update `cloud.google.com/go` dependency to [v0.73.0](https://github.com/googleapis/google-cloud-go/tree/v0.73.0) which is the latest available and has the [following changes](https://github.com/googleapis/google-cloud-go/releases/tag/v0.73.0)
- Update `cloud.google.com/go/logging` dependency to [v1.1.2](https://github.com/googleapis/google-cloud-go/tree/logging/v1.1.2) which is the latest available and has the [following changes](https://github.com/googleapis/google-cloud-go/releases/tag/logging%2Fv1.1.2)
- Update `github.com/GoogleCloudPlatform/testgrid` dependency to [v0.0.32](https://github.com/GoogleCloudPlatform/testgrid/tree/v0.0.32) which is the latest available and has the [following changes](https://github.com/GoogleCloudPlatform/testgrid/releases/tag/v0.0.32)
- Update `github.com/containers/image/v5` dependency to [v5.9.0](https://github.com/containers/image/tree/v5.9.0) which is the latest available and has the [following changes](https://github.com/containers/image/releases/tag/v5.9.0)
- Update `github.com/google/go-containerregistry` dependency to [v0.2.1](https://github.com/google/go-containerregistry/tree/v0.2.1) which is the latest available and has the [following changes](https://github.com/google/go-containerregistry/releases/tag/v0.2.1)
- Update `github.com/mitchellh/mapstructure` dependency to [v1.4.0](https://github.com/mitchellh/mapstructure/tree/v1.4.0) which is the latest available and has the [following changes](https://github.com/mitchellh/mapstructure/releases/tag/v1.4.0)
- Update `github.com/sendgrid/sendgrid-go` dependency to [v3.7.2](https://github.com/sendgrid/sendgrid-go/tree/v3.7.2) which is the latest available and has the [following changes](https://github.com/sendgrid/sendgrid-go/releases/tag/v3.7.2)
- Update `github.com/shirou/gopsutil/v3` dependency to [v3.20.11](https://github.com/shirou/gopsutil/tree/v3.20.11) which is the latest available and has the [following changes](https://github.com/shirou/gopsutil/releases/tag/v3.20.11)
- Update `google.golang.org/api` dependency to [v0.36.0](https://github.com/googleapis/google-api-go-client/tree/v0.36.0) which is the latest available and has the [following changes](https://github.com/googleapis/google-api-go-client/releases/tag/v0.36.0)
- Update `gopkg.in/yaml.v2` dependency to [v2.4.0](https://github.com/go-yaml/yaml/tree/v2.4.0) which is the latest available and has the [following changes](https://github.com/go-yaml/yaml/releases/tag/v2.4.0)
- Update `golang.org/x/net` dependency to `v0.0.0-20201207224615-747e23833adb`
- Update `golang.org/x/oauth2` dependency to `v0.0.0-20201208152858-08078c50e5b5`
- Update `google.golang.org/genproto` dependency to `v0.0.0-20201207150747-9ee31aac76e7`

/hold till patch releases are out

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
- Update `cloud.google.com/go` dependency to `v0.73.0`
- Update `cloud.google.com/go/logging` dependency to `v1.1.2`
- Update `github.com/GoogleCloudPlatform/testgrid` dependency to `v0.0.32`
- Update `github.com/containers/image/v5` dependency to `v5.9.0`
- Update `github.com/google/go-containerregistry` dependency to `v0.2.1`
- Update `github.com/mitchellh/mapstructure` dependency to `v1.4.0`
- Update `github.com/sendgrid/sendgrid-go` dependency to `v3.7.2`
- Update `github.com/shirou/gopsutil/v3` dependency to `v3.20.11`
- Update `google.golang.org/api` dependency to `v0.36.0`
- Update `gopkg.in/yaml.v2` dependency to `v2.4.0`
- Update `golang.org/x/net` dependency to `v0.0.0-20201207224615-747e23833adb`
- Update `golang.org/x/oauth2` dependency to `v0.0.0-20201208152858-08078c50e5b5`
- Update `google.golang.org/genproto` dependency to `v0.0.0-20201207150747-9ee31aac76e7`
```

/assign @hasheddan @saschagrunert

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
releases are out so will remove the hold

/hold cancel

**Pull request merged**
