### PR TITLE
add config for go1.20 for distroless-iptables

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup
/kind feature

#### What this PR does / why we need it:

Currently, we only build the distroless-iptables for the main branch, but the active release branches also get go updates and other dependencies, we also should update distrolless-iptables to the active branches and keep those up-to-date

- add config for go1.20 for distroless-iptables

/assign @jeremyrickard @saschagrunert @Verolop @ameukam 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
add config for go1.20 for distroless-iptables
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
@saschagrunert @jeremyrickard @xmudrii @kubernetes/release-engineering 

there are quite a few changes when we upgrade from bullseye to bookworm in the bash scripts, and will require to maintain both things, if that is fine I will make some adjustments to make that work, otherwise we will need to decide if the work makes sense

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
