### PR TITLE
Use correct release GCB substitutions

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
We now use the already existing functions to obtain the correct release
version on GCB job submit. This will ensure that the provided
substitutions are the same as those who get retrieved from krel.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Fixed wrong GCB substitutions for the release versions.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/hold
for manual testing

**Comment by saschagrunert** [comment]
/hold cancel

This works, now. I submitted the RC job and immediately aborted it afterwards because I just want to see the substitutions:
https://console.cloud.google.com/cloud-build/builds/ef84859b-997a-4d4c-afd7-e2160c685b1f;tab=detail?project=kubernetes-release-test

Looking good:
```
_BUILDVERSION             v1.20.0-beta.2.84+c1f36fa6f28d36
_MAJOR_VERSION_TAG        1
_PATCH_VERSION_TAG        0
_MINOR_VERSION_TAG        20
_KUBERNETES_VERSION_TAG   1.20.0-rc.0
```

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
