### PR TITLE
Bump mdtoc to v1.1.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Updating mdtoc to the latest release.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
Follow-up of https://github.com/kubernetes/release/pull/2275
#### Does this PR introduce a user-facing change?

```release-note
Fixed table of contents header links containing source code in changelog and release notes generation.
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by justaugustus — APPROVED** [review]

**Comment by saschagrunert** [comment]
Interesting: 
```
Error:      	Expected nil, but got: get latest GitHub tags: unable to retrieve GitHub tags: GET https://api.github.com/repos/kubernetes/kubernetes/tags?page=10&per_page=50: 403 API rate limit of 60 still exceeded until 2021-10-05 08:41:08 +0000 UTC, not making remote request. [rate reset in 28m20s]
```

**Comment by saschagrunert** [comment]
Testing that in https://github.com/kubernetes/release/pull/2278

**Pull request merged**
