### PR TITLE
Build Go 1.19.4 and 1.18.9 based images

### PR DESCRIPTION
**Pull request by xmudrii**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

- Build Go 1.19.4 and 1.18.9 based images
- Update references to kube-cross in `dependencies.yaml` from v1.25.0 to v1.26.0
- Add an entry for kube-cross v1.25.0 (previous release branch) to `dependencies.yaml`

#### Which issue(s) this PR fixes:

Part of #2788

#### Does this PR introduce a user-facing change?

```release-note
Build Go 1.19.4 and 1.18.9 based images
```

cc @kubernetes/release-engineering  @leonardpahlke

### CODE REVIEW

**Comment by xmudrii** [comment]
Looks like a combination of timeout and rate limit.
/retest

**Comment by palnabarun** [comment]
/test pull-release-integration-test
--

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
there is something wrong with the integration tests as we can see in a fresh test pr #2801 

i will look into it

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
