### PR TITLE
Refactor relnotes tools

### PR DESCRIPTION
**Pull request by hoegaarden**
I started investigating the release notes tooling and found it to be rel. slow.
I checked if there are some easy refactorings we could do and found quite some opportunities.
Because of the lack of testcoverage, I started to setup some isolated tests to guard the refactorings.

/kind cleanup

### CODE REVIEW

**Comment by justaugustus** [comment]
Sascha, are there any near-term remaining tweaks you're planning for relnotes.
I want to make sure you have an opportunity to land them before Hannes does some optimizations here.
/hold
/assign @saschagrunert

**Comment by saschagrunert** [comment]
> Sascha, are there any near-term remaining tweaks you're planning for relnotes.
> I want to make sure you have an opportunity to land them before Hannes does some optimizations here.
> /hold
> /assign @saschagrunert

Yes, I would like to add the proper mangling of the CHANGELOG markdown files in k/k. This is the only thing needed for a (test) replacement of the bash scripting.

I'm also willing to give this PR precedence because I think the optimizations are really great. It's up to you both :)

**Comment by hoegaarden** [comment]
/retitle Refactor relnotes tools

I think that's it for now. Besides improving test coverage it got a bit faster:

<details>

<summary>"benchmark"</summary>

```shell
± ha |slownotes → origin {10} ✓| → time go run ./cmd/release-notes/main.go --branch master --start-sha 70132b0f130acc0bed193d9ba59dd186f0e634cf --end-sha e622579b143730b89d471ecd4e5f6761e9c37d86
INFO fetching all commits. This might take a while...
INFO starting to process commit 1 of 175 (0.57%): e622579b143730b89d471ecd4e5f6761e9c37d86
INFO starting to process commit 2 of 175 (1.14%): c34d1402412e5f9e5f09847c1efec89c9adef3d2
  [...]
INFO starting to process commit 174 of 175 (99.43%): dd50ac311a0158f2f02589a311b0587b8f7eaa11
INFO starting to process commit 175 of 175 (100.00%): 93c9085e8a934c275445ec3ab2cb2662ab65774b
ERRO getting the release note from commit while listing release notes  err="no matches found when parsing note text from commit string" sha=414c838936571b7b9d48bba499c138bd1c5d693d
ERRO getting the release note from commit while listing release notes  err="no matches found when parsing note text from commit string" sha=cfb1389524c6be44157831252fed1d02ede59e00
INFO got the commits, performing rendering
INFO release notes written to file                 format=markdown path=/var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-782710897

real    0m7.534s
user    0m1.431s
sys     0m0.796s

± ha |slownotes → origin {10} ✓| → git co upstream/master && git describe
Note: switching to 'upstream/master'.
HEAD is now at d0d6b70 Merge pull request #969 from saschagrunert/cobra-release-notes
v0.2.0-24-gd0d6b70

± ha |detached:remotes/upstream/HEAD {10} ✓| → time go run ./cmd/release-notes/main.go --branch master --start-sha 70132b0f130acc0bed193d9ba59dd186f0e634cf --end-sha e622579b143730b89d471ecd4e5f6761e9c37d86
INFO fetching all commits. This might take a while...
INFO [1/175 - 0.57%]: e622579b143730b89d471ecd4e5f6761e9c37d86
INFO [2/175 - 1.14%]: c34d1402412e5f9e5f09847c1efec89c9adef3d2
  [...]
INFO [174/175 - 99.43%]: dd50ac311a0158f2f02589a311b0587b8f7eaa11
INFO [175/175 - 100.00%]: 93c9085e8a934c275445ec3ab2cb2662ab65774b
ERRO getting the release note from commit while listing release notes  err="no matches found when parsing note text from commit string" sha=414c838936571b7b9d48bba499c138bd1c5d693d
ERRO getting the release note from commit while listing release notes  err="no matches found when parsing note text from commit string" sha=cfb1389524c6be44157831252fed1d02ede59e00
INFO got the commits, performing rendering
INFO release notes written to file                 format=markdown path=/var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-666559311

real    1m9.369s
user    0m1.601s
sys     0m0.829s

± ha |slownotes → origin {10} ✓| → ls -l /var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-666559311 /var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-782710897
-rw-------  1 pivotal  staff  7125 13 Dec 15:18 /var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-666559311
-rw-------  1 pivotal  staff  7125 13 Dec 15:16 /var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-782710897

± ha |detached:remotes/upstream/HEAD {10} ✓| →
```

</details>

However, I also want to call out:
- never trust any benchmarks
- The 2 result files do differ, the ordering might change -- do we care?

```diff
--- /var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-666559311    2019-12-13 15:18:19.940491207 +0000
+++ /var/folders/m9/b02_gtzd17zb5d3h1mg8yhvr0000gn/T/release-notes-782710897    2019-12-13 15:16:53.895821457 +0000
@@ -9,9 +9,6 @@
 - SafeSysctlWhitelist: add net.ipv4.ping_group_range ([#85463](https://github.com/kubernetes/kubernetes/pull/85463), [@AkihiroSuda](https://github.com/AkihiroSuda))

   Courtesy of SIG Auth
-- kubelet: the metric process_start_time_seconds be marked as with the ALPHA stability level. ([#85446](https://github.com/kubernetes/kubernetes/pull/85446), [@RainbowMango](https://github.com/RainbowMango))
-
-  Courtesy of SIG API Machinery, SIG Cluster Lifecycle, SIG Instrumentation, and SIG Node
 - API request throttling (due to a high rate of requests) is now reported in the kubelet (and other component) logs by default.  The messages are of the form

   Throttling request took 1.50705208s, request: GET:<URL>
@@ -19,6 +16,9 @@
   The presence of large numbers of these messages, particularly with long delay times, may indicate to the administrator the need to tune the cluster accordingly. ([#80649](https://github.com/kubernetes/kubernetes/pull/80649), [@RobertKrawitz](https://github.com/RobertKrawitz))

   Courtesy of SIG API Machinery, and SIG Node
+- kubelet: the metric process_start_time_seconds be marked as with the ALPHA stability level. ([#85446](https://github.com/kubernetes/kubernetes/pull/85446), [@RainbowMango](https://github.com/RainbowMango))
+
+  Courtesy of SIG API Machinery, SIG Cluster Lifecycle, SIG Instrumentation, and SIG Node
 - kubectl/drain: add skip-wait-for-delete-timeout option.
   If pod DeletionTimestamp older than N seconds, skip waiting for the pod.  Seconds must be greater than 0 to skip. ([#85577](https://github.com/kubernetes/kubernetes/pull/85577), [@michaelgugino](https://github.com/michaelgugino))
```

**Comment by hoegaarden** [comment]
> Yes, I would like to add the proper mangling of the CHANGELOG markdown files in k/k. This is the only thing needed (beside #975) for a (test) replacement of the bash scripting.
> I'm also willing to give this PR precedence because I think the optimizations are really great. It's up to you both :)

I don't care. I am happy to wait with stuffs until you are done with your stuffs 😄

**Comment by justaugustus** [comment]
Let's land this optimization first then.
@saschagrunert -- Let me know when you have a chance to review this.

**Comment by saschagrunert** [comment]
Did a review and I see some small nits, but I don’t think this should block these awesome improvements. Thank you 🙏, this is exactly the way how I expect that this community works.

/lgtm
/approve

**Comment by saschagrunert** [comment]
Let’s release the hold @justaugustus :)

**Comment by justaugustus** [comment]
Away we go!
/hold cancel

**Comment by hoegaarden** [comment]
> Did a review and I see some small nits

@saschagrunert 
Thanks. Please let me know about the nits (open an issue, or comment on the merged PR) and I will address them!

**Pull request merged**
