### PR TITLE
Add coverage to go-test target

### PR DESCRIPTION
**Pull request by saschagrunert**
This outputs a `coverage.{html,out}` file for unit test coverage
inspection. I had to disable the race detection for now since it seems
that we introduced data races in our tests with the latest changes.

### CODE REVIEW

**Comment by hoegaarden** [comment]
Yeah, we should enable the race detection eventually, should be be fine once #977 (https://github.com/kubernetes/release/pull/977/commits/c586a8322f9b61217ce8aa3c7693a1c16995fb82) is merged.

Thanks

/lgtm
/approve

**Comment by saschagrunert** [comment]
Rebased on the latest master.

**Comment by hoegaarden** [comment]
So it seems that we run `bazel test //...` and we do not run `make test` (and thus `./hack/test*`) on prow.
Does anyone know why that is? Why do we have 2 divergent systems that have different definitions of what commit blocking means?

And based on that:
- Do we want to remove the duplication, and just use one way? We can have the one call the other if we'd want to.
- How would I go about changing what `go_default_test` means? E.g. how would I configure that we want to run with race-detection enabled or not?

Never the less:
/lgtm
/approve

**Pull request merged**
