### PR TITLE
Fix anago checks for buildversion

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The check was too early before applying this patch which caused an error
in the logs:

```
Step #3: ./anago: line 165: common::exit: command not found
Step #3: ./anago: line 167: logecho: command not found
```
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
:hourglass: Stage test logs: https://console.cloud.google.com/cloud-build/builds/43fda7f5-264e-49aa-82c0-5174b5265970?project=648026197307

**Comment by saschagrunert** [comment]
Works, errors are gone and the output is correct:
```
Step #3: ATTENTION: Using --buildversion=v1.20.0-alpha.0.1624+51ffb495f752fa
```

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
