### PR TITLE
Updates for k8s-cloud-builder and k8s-ci-builder 

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Since the golang updates in k/k are merged we now can bump the internal
image versions, too.

#### Which issue(s) this PR fixes:
Part of https://github.com/kubernetes/release/issues/1940

#### Special notes for your reviewer:
/assign @justaugustus @saschagrunert @hasheddan @puerco @xmudrii 
/hold
#### Does this PR introduce a user-facing change?

```release-note
Update k8s-cloud-builder to v1.15.10-1 and v1.15.10-legacy-1
Update k8s-ci-builder to use go 1.15.10 for 1.20/1.19 branches
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
ok for `k8s-ci-builder` the release tools need go1.16

```
#19 43.38 pkg/cip/dockerregistry/grow_manifest.go:141:9: undefined: os.WriteFile
#19 43.38 pkg/cip/dockerregistry/inventory.go:134:12: undefined: os.ReadFile
#19 43.38 pkg/cip/dockerregistry/inventory.go:161:12: undefined: os.ReadFile
#19 43.38 pkg/cip/dockerregistry/inventory.go:199:12: undefined: os.ReadFile
#19 43.38 pkg/cip/dockerregistry/inventory.go:321:16: undefined: os.ReadDir
#19 43.38 pkg/cip/dockerregistry/inventory.go:1097:13: undefined: io.ReadAll
#19 43.38 note: module requires Go 1.16
```

some options:
- revert the release-tools to still accept go1.15
- move all the things to be go1.16 including release branches in k/k

thoughts? or how we should proceed?

@saschagrunert @hasheddan @justaugustus for advice

**Comment by cpanato** [comment]
@saschagrunert @justaugustus @hasheddan gently ping, seeking advice in how we want to proceed

**Comment by saschagrunert** [comment]
I think we can use the latest go 1.16 for `k8s-ci-builder`, since it mainly runs `krel ci-build` which does not affect the code in k/k.

**Comment by cpanato** [comment]
dropped the config for 1.17 and made 1.20/1.19/1.18 to use go 1.16

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
