### PR TITLE
Refactor image building

### PR DESCRIPTION
**Pull request by hoegaarden**
- each image has its directory in `./images/` (~`./build/` has been renamed to `./images/`~)
- all follow the same pattern for that directory:
  - there is a `Dockerfile`
  - there is a couldbuilder config `cloudbuild.yaml`
  - the directory's content is uploaded to cloud build and used as a build context
- new makefile targets have been introduced that update (all currently used) images
- added Documentation how images can be built

/assign @justaugustus

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
(for my review)

**Comment by hoegaarden** [comment]
> Can we only move the Dockerfile-related things to images/ and copy in the OWNERS file?

Good catch re: the OWNERS file!

I was also thinking about renaming `./build` to `./packages`. But I'll just leave that here for now instead to gauge appetite -- we can always do that in another PR.

**Comment by justaugustus** [comment]
> I was also thinking about renaming `./build` to `./packages`. But I'll just leave that here for now instead to gauge appetite -- we can always do that in another PR.

I actually want to keep it as `build/` as it mirrors k/k, where [we _may_ eventually want to move these things to](https://github.com/kubernetes/kubernetes/issues/71677).

e.g., https://github.com/kubernetes/release/pull/818 was a step towards synchronizing what's in k/k/build and k/r/build

**Comment by justaugustus** [comment]
Great cleanup, @hoegaarden!
/lgtm
/approve
/hold cancel

**Comment by justaugustus** [comment]
/override pull-release-unit
(context: https://github.com/kubernetes/test-infra/pull/13890)

**Pull request merged**
