### PR TITLE
Compress release archive sources

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now compress the sources before copying them into the GCB archive
directory. This allows us faster retrieval of those sources.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/hold for the patches
#### Does this PR introduce a user-facing change?

```release-note
Changed archived Kubernetes release sources to be compressed as tarball
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

/hold dont know if we want that for the patch releases, feel free to remove

**Comment by saschagrunert** [comment]
Run in GCB works: https://console.cloud.google.com/cloud-build/builds/bb484313-dfe3-43c7-a125-e0625a1f9cb0?project=kubernetes-release-test

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
