### PR TITLE
Build Go 1.20.2 and 1.19.7 based images

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

- Build Go 1.20.2 and 1.19.7 based images

#### Which issue(s) this PR fixes:

Part of #2948

#### Does this PR introduce a user-facing change?

```release-note
Build Go 1.20.2 and 1.19.7 based images
```

/assign @saschagrunert @xmudrii @palnabarun @Verolop 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by cpanato** [comment]
images are not available
 
```
manifest for golang:1.20.2-bullseye not found: manifest unknown: manifest unknown
```


/hold

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
