### PR TITLE
Add support for command pipes

### PR DESCRIPTION
**Pull request by saschagrunert**
We now add support for running piped commands like:
```golang
command.New("ls", "-l").Pipe("wc", "-l").Run()
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
It's kinda fancy but I have the feeling that the increasing complexity it dramatically. :thinking:

**Comment by saschagrunert** [comment]
This is ready for review, please take a look :innocent:

**Comment by saschagrunert** [comment]
Found a bug
/hold

**Comment by saschagrunert** [comment]
Fixed
/hold-cancel

**Comment by justaugustus** [comment]
Ditto to what Carlos said!
/lgtm
/approve

**Pull request merged**
