### PR TITLE
Build go1.18 official images

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Part of https://github.com/kubernetes/release/issues/2307.

`its-happening.jpg`

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @puerco @cpanato @xmudrii 
cc: @kubernetes/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
Build go1.18 official images
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
yay
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by cpanato** [comment]
checking

**Comment by cpanato** [comment]
@justaugustus i'm watching the post submits jobs and will do the promotion as soon those are passing/green

**Pull request merged**
