### PR TITLE
Add dedicated HTTP package to be testable

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

We now use a dedicated, mock-able http package which is used by the
changelog retrieval and the release package. Tests have been added as
well.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
> This looks pretty good @saschagrunert! I was wondering though, is there any reason we cannot continue to use the built in http package and test with httptest? I have found this to work well in other places

I think so, I just forgot that this package exist :grin: Let me check if I can change the implementation 
/hold

**Comment by saschagrunert** [comment]
Changed the tests to use `httptest`
/hold cancel

**Comment by hasheddan** [comment]
@saschagrunert I was more thinking that we just use standard `http` package and then mock responses with `httptest`. What do you think?

**Comment by saschagrunert** [comment]
> @saschagrunert I was more thinking that we just use standard `http` package and then mock responses with `httptest`. What do you think?

Im wondering what the benefit of this approach is. :) we would still have to write an interface by ourself and do not have the counterfeiter helpers, right?

**Comment by hasheddan** [comment]
I think the benefit is that we do not have to maintain a wrapper. With `httptest` you can do something like this:
```
server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
  _ = r.Body.Close()
  if diff := cmp.Diff(http.MethodGet, r.Method); diff != "" {
    t.Errorf("r: -want, +got:\n%s", diff)
  }
  w.WriteHeader(http.StatusBadRequest)
  _ = json.NewEncoder(w).Encode(&github.Repository{})
}))

defer server.Close()
```

Then run any tests that use `http` and their requests will be intercepted by the handler(s).

**Comment by saschagrunert** [comment]
> I think the benefit is that we do not have to maintain a wrapper. With `httptest` you can do something like this:
> 
> ```
> server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
>   _ = r.Body.Close()
>   if diff := cmp.Diff(http.MethodGet, r.Method); diff != "" {
>     t.Errorf("r: -want, +got:\n%s", diff)
>   }
>   w.WriteHeader(http.StatusBadRequest)
>   _ = json.NewEncoder(w).Encode(&github.Repository{})
> }))
> 
> defer server.Close()
> ```
> 
> Then run any tests that use `http` and their requests will be intercepted by the handler(s).

Alright, changed as suggested :)

**Pull request merged**
