### PR TITLE
Don't use a SSH URL when cloning k/sig-release during krel website PR generation

### PR DESCRIPTION
**Pull request by JamesLaverack**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Fixes an issue where `krel release-notes` executed with the `--create-website-pr` flag would fail to clone kubenretes/sig-release.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
Fixed use of --create-website-pr flag to krel release-notes
```

### CODE REVIEW

**Comment by JamesLaverack** [comment]
Should I raise a GitHub issue for this PR to close? Or is the PR alone sufficient?

**Comment by puerco** [comment]
It seems to me that this was an auth problem on github. I'm posting here the output [reported on slack ](https://kubernetes.slack.com/archives/CN1KH4K9A/p1604631934102100) to test it later :
```
$ krel release-notes --create-website-pr --fix --fork jameslaverack --tag v1.20.0-beta.1
INFO Checking if a PR can be created from jameslaverack/release-notes
INFO Generating release notes for tag v1.20.0-beta.1
INFO Cloning kubernetes/sig-release to read mapping files
FATA creating website PR: generating release notes in JSON format: performing clone of k/sig-release: unable to clone repo: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by saschagrunert** [comment]
> It seems to me that this was an auth problem on github. I'm posting here the output [reported on slack ](https://kubernetes.slack.com/archives/CN1KH4K9A/p1604631934102100) to test it later :

So I assume that this PR is not necessary any more?

**Comment by saschagrunert** [comment]
/close

Feel free to reopen if this is still necessary.

**Comment by puerco** [comment]
The issue showed up again, let's merge it.
slack ref:  https://kubernetes.slack.com/archives/CJH2GBF7Y/p1612391308140500?thread_ts=1612343060.127500&cid=CJH2GBF7Y

/reopen

**Pull request merged**
