### PR TITLE
Cleanup Dockerfile for k8s-cloud-builder

### PR DESCRIPTION
**Pull request by hoegaarden**
... and add some tests for the most important commands we expect to have
available.

Some important changes:
- Only the docker CLI is installed, not the docker daemon:
  As far as I can see, we don't need the docker daemon here, we don't run d-in-d. This removes also a whole bunch of other things only needed by the daemon (iptables & other networking bits, aufs, kmod, ...)
- Most (all?) of the C/C++ compilers have been removed:
  I don't think we need them. The only thing we would use C for is building the pause image, and I don't think we do this (right now at least) from within this image.

/kind cleanup
/assign @tpepper @justaugustus 

<details><summary>Difference in installed packages compared to the <a href="//github.com/kubernetes/release/blob/40b138e4063ce4f0574585f5d0d87c1d2ea9cf38/images/k8s-cloud-builder/Dockerfile">the older version <tt>40b138e</tt></a></summary>

`-` means those packages are only in the original version of the image
`+` means those packages are only in the new version of the image

```diff
--- /tmp/org.pkg.list	2019-11-27 12:01:11.624565684 +0000
+++ /tmp/new.pkg.list	2019-11-27 15:02:57.723364089 +0000
@@ -2,8 +2,6 @@
 ii  apt                                    1.8.2                       amd64        commandline package manager
 ii  apt-transport-https                    1.8.2                       all          transitional package for https support
 ii  apt-utils                              1.8.2                       amd64        package management related utility programs
-ii  aufs-dkms                              4.19+20190211-1             all          DKMS files to build and install aufs
-ii  aufs-tools                             1:4.14+20190211-1           amd64        Tools to manage aufs filesystems
 ii  base-files                             10.3+deb10u1                amd64        Debian base system miscellaneous files
 ii  base-passwd                            3.5.46                      amd64        Debian base system master password and group files
 ii  bash                                   5.0-4                       amd64        GNU Bourne Again SHell
@@ -17,36 +15,19 @@
 ii  bsdutils                               1:2.33.1-0.1                amd64        basic utilities from 4.4BSD-Lite
 ii  bzip2                                  1.0.6-9.2~deb10u1           amd64        high-quality block-sorting file compressor - utilities
 ii  ca-certificates                        20190110                    all          Common CA certificates
-ii  cgroupfs-mount                         1.4                         all          Light-weight package to set up cgroupfs mounts
-ii  containerd.io                          1.2.10-3                    amd64        An open and reliable container runtime
 ii  coreutils                              8.30-3                      amd64        GNU core utilities
-ii  cpp                                    4:8.3.0-1                   amd64        GNU C preprocessor (cpp)
-ii  cpp-8                                  8.3.0-6                     amd64        GNU C preprocessor
-ii  cpp-8-aarch64-linux-gnu                8.3.0-2cross1               amd64        GNU C preprocessor
-ii  cpp-8-arm-linux-gnueabihf              8.3.0-2cross1               amd64        GNU C preprocessor
-ii  cpp-8-powerpc64le-linux-gnu            8.3.0-2cross1               amd64        GNU C preprocessor
-ii  cpp-8-s390x-linux-gnu                  8.3.0-2cross1               amd64        GNU C preprocessor
-ii  cpp-aarch64-linux-gnu                  4:8.3.0-1                   amd64        GNU C preprocessor (cpp) for the arm64 architecture
-ii  cpp-arm-linux-gnueabihf                4:8.3.0-1                   amd64        GNU C preprocessor (cpp) for the armhf architecture
-ii  cpp-powerpc64le-linux-gnu              4:8.3.0-1                   amd64        GNU C preprocessor (cpp) for the ppc64el architecture
-ii  cpp-s390x-linux-gnu                    4:8.3.0-1                   amd64        GNU C preprocessor (cpp) for the s390x architecture
 ii  cross-config                           2.6.15-3                    all          autotools support for cross-compilation
-ii  crossbuild-essential-arm64             12.6                        all          Informational list of cross-build-essential packages
-ii  crossbuild-essential-armhf             12.6                        all          Informational list of cross-build-essential packages
-ii  crossbuild-essential-ppc64el           12.6                        all          Informational list of cross-build-essential packages
-ii  crossbuild-essential-s390x             12.6                        all          Informational list of cross-build-essential packages
 ii  curl                                   7.64.0-4                    amd64        command line tool for transferring data with URL syntax
 ii  dash                                   0.5.10.2-5                  amd64        POSIX-compliant shell
 ii  dbus                                   1.12.16-1                   amd64        simple interprocess messaging system (daemon and utilities)
 ii  debconf                                1.5.71                      all          Debian configuration management system
 ii  debian-archive-keyring                 2019.1                      all          GnuPG archive keys of the Debian archive
 ii  debianutils                            4.8.6.1                     amd64        Miscellaneous utilities specific to Debian
+ii  dh-python                              3.20190308                  all          Debian helper tools for packaging Python libraries and applications
 ii  diffutils                              1:3.7-3                     amd64        File comparison utilities
 ii  dirmngr                                2.2.12-1+deb10u1            amd64        GNU privacy guard - network certificate management service
 ii  distro-info-data                       0.41+deb10u1                all          information about the distributions' releases (data files)
-ii  dkms                                   2.6.1-4                     all          Dynamic Kernel Module Support Framework
 ii  dmsetup                                2:1.02.155-3                amd64        Linux Kernel Device Mapper userspace library
-ii  docker-ce                              5:19.03.5~3-0~debian-buster amd64        Docker: the open-source application container engine
 ii  docker-ce-cli                          5:19.03.5~3-0~debian-buster amd64        Docker CLI: the open-source application container engine
 ii  dpkg                                   1.19.7                      amd64        Debian package management system
 ii  dpkg-cross                             2.6.15-3                    all          tools for cross compiling Debian packages
@@ -56,31 +37,12 @@
 ii  fdisk                                  2.33.1-0.1                  amd64        collection of partitioning utilities
 ii  file                                   1:5.35-4+deb10u1            amd64        Recognize the type of data in a file using "magic" numbers
 ii  findutils                              4.6.0+git+20190209-2        amd64        utilities for finding files--find, xargs
-ii  g++-8                                  8.3.0-6                     amd64        GNU C++ compiler
-ii  g++-8-aarch64-linux-gnu                8.3.0-2cross1               amd64        GNU C++ compiler
-ii  g++-8-arm-linux-gnueabihf              8.3.0-2cross1               amd64        GNU C++ compiler
-ii  g++-8-powerpc64le-linux-gnu            8.3.0-2cross1               amd64        GNU C++ compiler
-ii  g++-8-s390x-linux-gnu                  8.3.0-2cross1               amd64        GNU C++ compiler
-ii  g++-aarch64-linux-gnu                  4:8.3.0-1                   amd64        GNU C++ compiler for the arm64 architecture
-ii  g++-arm-linux-gnueabihf                4:8.3.0-1                   amd64        GNU C++ compiler for the armhf architecture
-ii  g++-powerpc64le-linux-gnu              4:8.3.0-1                   amd64        GNU C++ compiler for the ppc64el architecture
-ii  g++-s390x-linux-gnu                    4:8.3.0-1                   amd64        GNU C++ compiler for the s390x architecture
-ii  gcc                                    4:8.3.0-1                   amd64        GNU C compiler
-ii  gcc-8                                  8.3.0-6                     amd64        GNU C compiler
-ii  gcc-8-aarch64-linux-gnu                8.3.0-2cross1               amd64        GNU C compiler
 ii  gcc-8-aarch64-linux-gnu-base:amd64     8.3.0-2cross1               amd64        GCC, the GNU Compiler Collection (base package)
-ii  gcc-8-arm-linux-gnueabihf              8.3.0-2cross1               amd64        GNU C compiler
 ii  gcc-8-arm-linux-gnueabihf-base:amd64   8.3.0-2cross1               amd64        GCC, the GNU Compiler Collection (base package)
 ii  gcc-8-base:amd64                       8.3.0-6                     amd64        GCC, the GNU Compiler Collection (base package)
 ii  gcc-8-cross-base                       8.3.0-2cross1               all          GCC, the GNU Compiler Collection (library base package)
-ii  gcc-8-powerpc64le-linux-gnu            8.3.0-2cross1               amd64        GNU C compiler
 ii  gcc-8-powerpc64le-linux-gnu-base:amd64 8.3.0-2cross1               amd64        GCC, the GNU Compiler Collection (base package)
-ii  gcc-8-s390x-linux-gnu                  8.3.0-2cross1               amd64        GNU C compiler
 ii  gcc-8-s390x-linux-gnu-base:amd64       8.3.0-2cross1               amd64        GCC, the GNU Compiler Collection (base package)
-ii  gcc-aarch64-linux-gnu                  4:8.3.0-1                   amd64        GNU C compiler for the arm64 architecture
-ii  gcc-arm-linux-gnueabihf                4:8.3.0-1                   amd64        GNU C compiler for the armhf architecture
-ii  gcc-powerpc64le-linux-gnu              4:8.3.0-1                   amd64        GNU C compiler for the ppc64el architecture
-ii  gcc-s390x-linux-gnu                    4:8.3.0-1                   amd64        GNU C compiler for the s390x architecture
 ii  gettext-base                           0.19.8.1-9                  amd64        GNU Internationalization utilities for the base system
 ii  gir1.2-glib-2.0:amd64                  1.58.3-2                    amd64        Introspection data for GLib, GObject, Gio and GModule
 ii  gir1.2-packagekitglib-1.0              1.1.12-5                    amd64        GObject introspection data for the PackageKit GLib library
@@ -102,11 +64,9 @@
 ii  hostname                               3.21                        amd64        utility to set/show the host name or domain name
 ii  init-system-helpers                    1.56+nmu1                   all          helper tools for all init systems
 ii  iproute2                               4.20.0-2                    amd64        networking and traffic control tools
-ii  iptables                               1.8.2-4                     amd64        administration tools for packet filtering and NAT
 ii  iputils-ping                           3:20180629-2                amd64        Tools to test the reachability of network hosts
 ii  iso-codes                              4.2-1                       all          ISO language, territory, currency, script codes and their translations
 ii  jq                                     1.5+dfsg-2+b1               amd64        lightweight and flexible command-line JSON processor
-ii  kmod                                   26-1                        amd64        tools for managing Linux kernel modules
 ii  libacl1:amd64                          2.2.53-4                    amd64        access control list - shared library
 ii  libalgorithm-diff-perl                 1.19.03-2                   all          module to find differences between files
 ii  libalgorithm-diff-xs-perl              0.04-5+b1                   amd64        module to find differences between files (XS accelerated)
@@ -225,14 +185,11 @@
 ii  libio-socket-ssl-perl                  2.060-3                     all          Perl module implementing object oriented interface to SSL sockets
 ii  libio-string-perl                      1.08-3                      all          Emulate IO::File interface for in-core strings
 ii  libip4tc0:amd64                        1.8.2-4                     amd64        netfilter libip4tc library
-ii  libip6tc0:amd64                        1.8.2-4                     amd64        netfilter libip6tc library
-ii  libiptc0:amd64                         1.8.2-4                     amd64        netfilter libiptc library
 ii  libisl19:amd64                         0.20-2                      amd64        manipulating sets and relations of integer points bounded by linear constraints
 ii  libitm1:amd64                          8.3.0-6                     amd64        GNU Transactional Memory Library
 ii  libitm1-arm64-cross                    8.3.0-2cross1               all          GNU Transactional Memory Library
 ii  libitm1-ppc64el-cross                  8.3.0-2cross1               all          GNU Transactional Memory Library
 ii  libitm1-s390x-cross                    8.3.0-2cross1               all          GNU Transactional Memory Library
-ii  libjansson4:amd64                      2.12-1                      amd64        C library for encoding, decoding and manipulating JSON data
 ii  libjq1:amd64                           1.5+dfsg-2+b1               amd64        lightweight and flexible command-line JSON processor - shared library
 ii  libjson-c3:amd64                       0.12.1+ds-2                 amd64        JSON manipulation library - shared library
 ii  libk5crypto3:amd64                     1.17-3                      amd64        MIT Kerberos runtime libraries - Crypto Library
@@ -247,7 +204,6 @@
 ii  liblsan0:amd64                         8.3.0-6                     amd64        LeakSanitizer -- a memory leak detector (runtime)
 ii  liblsan0-arm64-cross                   8.3.0-2cross1               all          LeakSanitizer -- a memory leak detector (runtime)
 ii  liblsan0-ppc64el-cross                 8.3.0-2cross1               all          LeakSanitizer -- a memory leak detector (runtime)
-ii  libltdl7:amd64                         2.4.6-9                     amd64        System independent dlopen wrapper for GNU libtool
 ii  liblua5.1-0:amd64                      5.1.5-8.1+b2                amd64        Shared library for the Lua interpreter version 5.1
 ii  liblwp-mediatypes-perl                 6.02-1                      all          module to guess media type for a file or a URL
 ii  liblwp-protocol-https-perl             6.07-2                      all          HTTPS driver for LWP::UserAgent
@@ -267,11 +223,7 @@
 ii  libnet-http-perl                       6.18-1                      all          module providing low-level HTTP connection client
 ii  libnet-smtp-ssl-perl                   1.04-1                      all          Perl module providing SSL support to Net::SMTP
 ii  libnet-ssleay-perl                     1.85-2+b1                   amd64        Perl module for Secure Sockets Layer (SSL)
-ii  libnetfilter-conntrack3:amd64          1.0.7-1                     amd64        Netfilter netlink-conntrack library
 ii  libnettle6:amd64                       3.4.1-1                     amd64        low level cryptographic library (symmetric and one-way cryptos)
-ii  libnfnetlink0:amd64                    1.0.1-3+b1                  amd64        Netfilter netlink library
-ii  libnftables0:amd64                     0.9.0-2                     amd64        Netfilter nftables high level userspace API library
-ii  libnftnl11:amd64                       1.1.2-2                     amd64        Netfilter nftables userspace API library
 ii  libnghttp2-14:amd64                    1.36.0-2+deb10u1            amd64        library implementing HTTP/2 protocol (shared library)
 ii  libnpth0:amd64                         1.6-1                       amd64        replacement for GNU Pth using system threads
 ii  libnss-systemd:amd64                   241-7~deb10u2               amd64        nss module providing dynamic user and group name resolution
@@ -292,15 +244,10 @@
 ii  libpopt0:amd64                         1.16-12                     amd64        lib for parsing cmdline parameters
 ii  libprocps7:amd64                       2:3.3.15-2                  amd64        library for accessing process information from /proc
 ii  libpsl5:amd64                          0.20.2-2                    amd64        Library for Public Suffix List (shared libraries)
-ii  libpython-dev:amd64                    2.7.16-1                    amd64        header files and a static library for Python2
-ii  libpython-stdlib:amd64                 2.7.16-1                    amd64        interactive high-level object-oriented language (Python2)
-ii  libpython2-dev:amd64                   2.7.16-1                    amd64        header files and a static library for Python2
-ii  libpython2-stdlib:amd64                2.7.16-1                    amd64        interactive high-level object-oriented language (Python2)
-ii  libpython2.7:amd64                     2.7.16-2+deb10u1            amd64        Shared Python runtime library (version 2.7)
-ii  libpython2.7-dev:amd64                 2.7.16-2+deb10u1            amd64        Header files and a static library for Python (v2.7)
-ii  libpython2.7-minimal:amd64             2.7.16-2+deb10u1            amd64        Minimal subset of the Python language (version 2.7)
-ii  libpython2.7-stdlib:amd64              2.7.16-2+deb10u1            amd64        Interactive high-level object-oriented language (standard library, version 2.7)
+ii  libpython3-dev:amd64                   3.7.3-1                     amd64        header files and a static library for Python (default)
 ii  libpython3-stdlib:amd64                3.7.3-1                     amd64        interactive high-level object-oriented language (default python3 version)
+ii  libpython3.7:amd64                     3.7.3-2                     amd64        Shared Python runtime library (version 3.7)
+ii  libpython3.7-dev:amd64                 3.7.3-2                     amd64        Header files and a static library for Python (v3.7)
 ii  libpython3.7-minimal:amd64             3.7.3-2                     amd64        Minimal subset of the Python language (version 3.7)
 ii  libpython3.7-stdlib:amd64              3.7.3-2                     amd64        Interactive high-level object-oriented language (standard library, version 3.7)
 ii  libquadmath0:amd64                     8.3.0-6                     amd64        GCC Quad-Precision Math Library
@@ -365,11 +312,6 @@
 ii  libyaml-libyaml-perl                   0.76+repack-1               amd64        Perl interface to libyaml, a YAML implementation
 ii  libyaml-perl                           1.27-1                      all          YAML Ain't Markup Language
 ii  libzstd1:amd64                         1.3.8+dfsg-3                amd64        fast lossless compression algorithm
-ii  linux-compiler-gcc-8-x86               4.19.67-2+deb10u2           amd64        Compiler for Linux on x86 (meta-package)
-ii  linux-headers-4.19.0-6-amd64           4.19.67-2+deb10u2           amd64        Header files for Linux 4.19.0-6-amd64
-ii  linux-headers-4.19.0-6-common          4.19.67-2+deb10u2           all          Common header files for Linux 4.19.0-6
-ii  linux-headers-amd64                    4.19+105+deb10u1            amd64        Header files for Linux amd64 configuration (meta-package)
-ii  linux-kbuild-4.19                      4.19.67-2+deb10u2           amd64        Kbuild infrastructure for Linux 4.19
 ii  linux-libc-dev:amd64                   4.19.67-2+deb10u1           amd64        Linux support headers for userspace development
 ii  linux-libc-dev-arm64-cross             4.19.20-1cross1             all          Linux Kernel Headers for development (for cross-compiling)
 ii  linux-libc-dev-armhf-cross             4.19.20-1cross1             all          Linux Kernel Headers for development (for cross-compiling)
@@ -380,15 +322,12 @@
 ii  lsb-release                            10.2019051400               all          Linux Standard Base version reporting utility
 ii  make                                   4.2.1-1.2                   amd64        utility for directing compilation
 ii  mawk                                   1.3.3-17+b3                 amd64        a pattern scanning and text processing language
-ii  mercurial                              4.8.2-1+deb10u1             amd64        easy-to-use, scalable distributed version control system
-ii  mercurial-common                       4.8.2-1+deb10u1             all          easy-to-use, scalable distributed version control system (common files)
 ii  mime-support                           3.62                        all          MIME files 'mime.types' & 'mailcap', and support programs
 ii  mount                                  2.33.1-0.1                  amd64        tools for mounting and manipulating filesystems
 ii  ncurses-base                           6.1+20181013-2+deb10u1      all          basic terminal type definitions
 ii  ncurses-bin                            6.1+20181013-2+deb10u1      amd64        terminal-related programs and man pages
 ii  net-tools                              1.60+git20180626.aebd88e-1  amd64        NET-3 networking toolkit
 ii  netbase                                5.6                         all          Basic TCP/IP networking system
-ii  nftables                               0.9.0-2                     amd64        Program to control packet filtering rules by Netfilter project
 ii  openssh-client                         1:7.9p1-10+deb10u1          amd64        secure shell (SSH) client, for secure access to remote machines
 ii  openssl                                1.1.1d-0+deb10u2            amd64        Secure Sockets Layer toolkit - cryptographic utility
 ii  packagekit                             1.1.12-5                    amd64        Provides a package management service
@@ -401,30 +340,39 @@
 ii  perl-base                              5.28.1-6                    amd64        minimal Perl system
 ii  perl-modules-5.28                      5.28.1-6                    all          Core Perl modules
 ii  perl-openssl-defaults:amd64            3                           amd64        version compatibility baseline for Perl OpenSSL packages
-ii  pigz                                   2.4-1                       amd64        Parallel Implementation of GZip
 ii  pinentry-curses                        1.1.0-2                     amd64        curses-based PIN or pass-phrase entry dialog for GnuPG
 ii  pkg-config                             0.29-6                      amd64        manage compile and link flags for libraries
 ii  policykit-1                            0.105-25                    amd64        framework for managing administrative policies and privileges
 ii  procps                                 2:3.3.15-2                  amd64        /proc file system utilities
-ii  python                                 2.7.16-1                    amd64        interactive high-level object-oriented language (Python2 version)
 ii  python-apt-common                      1.8.4                       all          Python interface to libapt-pkg (locales)
-ii  python-minimal                         2.7.16-1                    amd64        minimal subset of the Python2 language
-ii  python-pkg-resources                   40.8.0-1                    all          Package Discovery and Resource Access using pkg_resources
-ii  python2                                2.7.16-1                    amd64        interactive high-level object-oriented language (Python2 version)
-ii  python2-dev                            2.7.16-1                    amd64        header files and a static library for Python2
-ii  python2-minimal                        2.7.16-1                    amd64        minimal subset of the Python2 language
-ii  python2.7                              2.7.16-2+deb10u1            amd64        Interactive high-level object-oriented language (version 2.7)
-ii  python2.7-dev                          2.7.16-2+deb10u1            amd64        Header files and a static library for Python (v2.7)
-ii  python2.7-minimal                      2.7.16-2+deb10u1            amd64        Minimal subset of the Python language (version 2.7)
+ii  python-pip-whl                         18.1-5                      all          Python package installer
 ii  python3                                3.7.3-1                     amd64        interactive high-level object-oriented language (default python3 version)
 ii  python3-apt                            1.8.4                       amd64        Python 3 interface to libapt-pkg
+ii  python3-asn1crypto                     0.24.0-1                    all          Fast ASN.1 parser and serializer (Python 3)
+ii  python3-cffi-backend                   1.12.2-1                    amd64        Foreign Function Interface for Python 3 calling C code - runtime
+ii  python3-crypto                         2.6.1-9+b1                  amd64        cryptographic algorithms and protocols for Python 3
+ii  python3-cryptography                   2.6.1-3+deb10u2             amd64        Python library exposing cryptographic recipes and primitives (Python 3)
 ii  python3-dbus                           1.2.8-3                     amd64        simple interprocess messaging system (Python 3 interface)
+ii  python3-dev                            3.7.3-1                     amd64        header files and a static library for Python (default)
 ii  python3-distro-info                    0.21                        all          information about distributions' releases (Python 3 module)
+ii  python3-distutils                      3.7.3-1                     all          distutils package for Python 3.x
+ii  python3-entrypoints                    0.3-1                       all          Discover and load entry points from installed packages (Python 3)
 ii  python3-gi                             3.30.4-1                    amd64        Python 3 bindings for gobject-introspection libraries
+ii  python3-keyring                        17.1.1-1                    all          store and access your passwords safely - Python 3 version of the package
+ii  python3-keyrings.alt                   3.1.1-1                     all          alternate backend implementations for python3-keyring
+ii  python3-lib2to3                        3.7.3-1                     all          Interactive high-level object-oriented language (2to3, version 3.6)
 ii  python3-minimal                        3.7.3-1                     amd64        minimal subset of the Python language (default python3 version)
+ii  python3-pip                            18.1-5                      all          Python package installer
+ii  python3-pkg-resources                  40.8.0-1                    all          Package Discovery and Resource Access using pkg_resources
 ii  python3-pycurl                         7.43.0.2-0.1                amd64        Python bindings to libcurl (Python 3)
+ii  python3-secretstorage                  2.3.1-2                     all          Python module for storing secrets - Python 3.x version
+ii  python3-setuptools                     40.8.0-1                    all          Python3 Distutils Enhancements
+ii  python3-six                            1.12.0-1                    all          Python 2 and 3 compatibility library (Python 3 interface)
 ii  python3-software-properties            0.96.20.2-2                 all          manage the repositories that you install software from
+ii  python3-wheel                          0.32.3-2                    all          built-package format for Python
+ii  python3-xdg                            0.25-5                      all          Python 3 library to access freedesktop.org standards
 ii  python3.7                              3.7.3-2                     amd64        Interactive high-level object-oriented language (version 3.7)
+ii  python3.7-dev                          3.7.3-2                     amd64        Header files and a static library for Python (v3.7)
 ii  python3.7-minimal                      3.7.3-2                     amd64        Minimal subset of the Python language (version 3.7)
 ii  readline-common                        7.0-5                       all          GNU readline and history libraries, common files
 ii  rsync                                  3.1.3-6                     amd64        fast, versatile, remote (and local) file-copying tool
@@ -432,7 +380,6 @@
 ii  sensible-utils                         0.0.12                      all          Utilities for sensible alternative selection
 ii  software-properties-common             0.96.20.2-2                 all          manage the repositories that you install software from (common)
 ii  subversion                             1.10.4-1+deb10u1            amd64        Advanced version control system
-ii  sudo                                   1.8.27-1+deb10u1            amd64        Provide limited super user privileges to specific users
 ii  systemd                                241-7~deb10u2               amd64        system and service manager
 ii  systemd-sysv                           241-7~deb10u2               amd64        system and service manager - SysV links
 ii  sysvinit-utils                         2.93-8                      amd64        System-V-like utilities

```

</details>

### CODE REVIEW

**Comment by hoegaarden** [comment]
explicit
/hold
for review and discussion of the potentially controversial changes.

**Comment by hoegaarden** [comment]
mock stage: https://console.cloud.google.com/cloud-build/builds/722046a0-2002-4c31-8781-6b8b9781467c?project=kubernetes-release-test&organizationId=433637338589
mock release: https://console.cloud.google.com/cloud-build/builds/e61ad3cc-b6ea-40e6-82ca-103fac2f1a63?project=kubernetes-release-test&organizationId=433637338589

**Comment by justaugustus** [comment]
/lgtm
/approve

Will leave this open for a bit for discussion.

**Comment by justaugustus** [comment]
Kubernetes 1.17.0 is out, so I'm releasing the hold on this.
I'll push the image out to `kubernetes-release-test` so we can try it out for this week's patch releases.
/hold cancel

**Comment by justaugustus** [comment]
Send notice to the @kubernetes/release-engineering group on the new image: https://groups.google.com/a/kubernetes.io/d/topic/release-managers/EsQuBm2HHS4/discussion

**Pull request merged**
