### PR TITLE
Ability to override BINFMT_IMAGE in init-buildx.sh

### PR DESCRIPTION
**Pull request by chewong**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

As someone who consumes this package downstream, I'd like to specify the binfmt image so I can bypass the docker throttling limit (similar to who I did to the GOLANG base image in https://github.com/kubernetes/release/pull/1967).

#### Which issue(s) this PR fixes:

N/A
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @jeremyrickard @xmudrii 
/approve
/lgtm

following the same precedent we've used before. looks good to me.

**Review by saschagrunert — APPROVED** [review]

**Comment by chewong** [comment]
Could someone help retrigger `CodeQL / Analyze`?

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
