### PR TITLE
Fix several typos/nits in comments

### PR DESCRIPTION
**Pull request by mattmoor**
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

I noticed a few typos and inconsistencies when reading the godoc for the spdx package.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

cc @puerco

### CODE REVIEW

**Comment by puerco** [comment]
Thanks @mattmoor ! I think the new EasyCLA check does not block PRs yet. Let's see
/ok-to-test

**Comment by mattmoor** [comment]
@puerco Dan is working on the EasyCLA stuff too now so 🤞

**Comment by puerco** [comment]
Tada! :tada:  :)
Thanks !

**Pull request merged**
