### PR TITLE
Update releaselib.sh for node binaries.

### PR DESCRIPTION
**Pull request by brendandburns**
@ixdy @pires @jbhurat

### CODE REVIEW

**Comment by pires** [comment]
So this will push _node_ binaries only when there are no server binaries, which basically means anything other than Linux, AND there are node binaries, which for now only matches Windows. If my reading is correct, LGTM.

**Comment by brendandburns** [comment]
@pires that is correct (I think :)

**Comment by brendandburns** [comment]
@ixdy what is the merge process for this repo? should I just press the button?

**Comment by ixdy** [comment]
@brendanburns yep, no bot here.

**Pull request merged**
