### PR TITLE
docs: Update link to promo tools documentation

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
Fixes link to kpromo docs.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
this looks like partially fixes https://github.com/kubernetes/release/issues/2388

**Review by cpanato — CHANGES_REQUESTED** [review]
thanks @jsturtevant for the docs updates

can you please also update the `gh2gcs` link in line 98

to be `https://github.com/kubernetes-sigs/promo-tools/blob/main/docs/github-promotion.md` ?

thanks!

**Review by justaugustus — APPROVED** [review]
Thanks @jsturtevant!

**Pull request merged**
