### PR TITLE
kube-cross: Support building against multiple Go versions in parallel

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

**Unblocks [Kubernetes 1.15.12 release](https://github.com/kubernetes/sig-release/issues/1051)**

- kube-cross: Minor Dockerfile reformat

  - apt package per line
  - dedupe and move apt cleanup to the last step

- kube-cross: Add k8s-cloud-builder functionality

  Currently the k8s-cloud-builder image depends on the kube-cross image
  version for staging/releasing Kubernetes. In our current state, we'd
  require a bump to the kube-cross version if the content of
  k8s-cloud-builder changes. This is both counter-intuitive and
  time-consuming from a promotion perspective.

  This commit moves the k8s-cloud-builder Dockerfile content into
  kube-cross allowing us to maintain a single image for
  building/staging/releasing Kubernetes.

- kube-cross: Add variants.yaml

  variants.yaml is a config file for the GCB builder (image
  building/pushing tool). By specifying variants, GCB builder will start
  multiple GCB jobs in parallel with the variants specified.

  Here we add a variants.yaml that defines separate Go versions to build
  in parallel.

- kube-cross: Enable variant building and bump version tags

  This is a refactor of the Dockerfile, Makefile, cloudbuild.yaml to
  properly substitute the variables specified in variants.yaml.

- gcb: Use kube-cross image instead of k8s-cloud-builder for stage/release

ref: https://github.com/kubernetes/release/issues/1257

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/hold for testing and commit cleanups

#### Does this PR introduce a user-facing change?

```release-note
kube-cross: Support building against multiple Go versions in parallel
```

### CODE REVIEW

**Comment by justaugustus** [comment]
@markyjackson-taulia @Verolop -- this was the fix I was referring to in https://github.com/kubernetes/release/issues/1257.

**Comment by justaugustus** [comment]
Looks like the images are building successfully, but I've got to fix the tag check at the end of the GCB config:

- go1.14: https://console.cloud.google.com/cloud-build/builds/1beebb0d-45f7-4063-8339-3db39f449926;tab=detail?project=k8s-staging-build-image
- go1.13: https://console.cloud.google.com/cloud-build/builds/23157e11-db18-4d2b-ae47-33397923ccbb;tab=detail?project=k8s-staging-build-image
- go1.12: https://console.cloud.google.com/cloud-build/builds/94e38643-d055-4cff-9f07-5c3c75d0717f;tab=detail?project=k8s-staging-build-image

**Comment by justaugustus** [comment]
The new image pushes were all successful at https://github.com/kubernetes/release/pull/1258/commits/076e864cf95666497b24375485c245a8d954d741:
- go1.14: https://console.cloud.google.com/cloud-build/builds/d67e100a-fc65-4ea7-bfe3-60af05ff17e9?project=k8s-staging-build-image --> gcr.io/k8s-staging-build-image/kube-cross-amd64@sha256:eb8243afbb0300900d4a87ac48d5aa8a2b6fb8d84ab3fe3bb9185c62edca396a
- go1.13: https://console.cloud.google.com/cloud-build/builds/26fd2533-a762-48c9-b626-a600e271995c?project=k8s-staging-build-image --> gcr.io/k8s-staging-build-image/kube-cross-amd64@sha256:5037ece668ccaa590c955afe41ca6c30a8e2eb3e22e2c56ada8162ee8fa6dfcd
- go1.12: https://console.cloud.google.com/cloud-build/builds/11c25db9-b19f-42dd-85c1-3c335a874594?project=k8s-staging-build-image --> gcr.io/k8s-staging-build-image/kube-cross-amd64@sha256:a8cc86ee4ed03627e745f0c0ca15d42cb36b32aca43630d495b0f0772cb36a9f

I've sent a PR to test the kube-cross in k/k@`release-1.15`: https://github.com/kubernetes/kubernetes/pull/90760
The first round of tests was successful and I've sent `pull-kubernetes-cross` for a retest now that new images have pushed.

The last step here (I believe) is verifying that the staging/release jobs work with the new kube-cross image. I'll be testing that shortly against the `release-1.15` branch.

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering 
/assign @tpepper @saschagrunert @cpanato @hasheddan 
cc: @dims @liggitt

**Comment by justaugustus** [comment]
Testing the 1.15.12 stage against https://github.com/kubernetes/release/pull/1258/commits/329053e54409723e33fd7061813cddc1007213a7 here: https://console.cloud.google.com/cloud-build/builds/29158b45-a286-4811-98c8-05d7a2623fa8?project=kubernetes-release-test

**Comment by justaugustus** [comment]
Test stage was successful, so I'm dropping the test commit.

**Comment by tpepper** [comment]
/lgtm
Generally this is really nice clean up!

One small nit/question: Would it make sense to go ahead and roll in a move to golang variant 1.13.10 instead of 1.13.9?

**Comment by justaugustus** [comment]
> One small nit/question: Would it make sense to go ahead and roll in a move to golang variant 1.13.10 instead of 1.13.9?

@tpepper --

I could've, but I wanted to:
1. minimize the variance in this PR
2. give @markyjackson-taulia and @Verolop an opportunity to work through the go1.13.10 update (ref: https://github.com/kubernetes/release/issues/1257)

---

Thanks for the reviews everyone!
/hold cancel

**Comment by dims** [comment]
LGTM

**Pull request merged**
