### PR TITLE
Remove unit file ExecStart

### PR DESCRIPTION
**Pull request by riverzhang**
Not execute anything

### CODE REVIEW

**Comment by riverzhang** [comment]
https://github.com/kubernetes/kubernetes/pull/59191

**Comment by kad** [comment]
removing empty `ExecStart=` will lead to broken .service file:
```
kad:/home/kad # systemctl show kubelet | grep ExecStart=
ExecStart={ path=/usr/bin/kubelet ; argv[]=/usr/bin/kubelet ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStart={ path=/usr/bin/kubelet ; argv[]=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
kad:/home/kad #
```

**Pull request closed without merging**
