### PR TITLE
Add krel changelog integration tests

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Added first `krel changelog` integration test cases. This also refactors the shared test-methods around the SUT (system under test) into a dedicated `sut_test.go` file.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

None

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready for review :heavy_check_mark:

**Comment by justaugustus** [comment]
Leaving others to take the review on this:
/assign @hasheddan @hoegaarden @cpanato 
/uncc

**Comment by saschagrunert** [comment]
Waiting for https://github.com/kubernetes/release/pull/1068 to rebase

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch to resolve conflicts. I also refactored code used in multiple locations into `sut_test.go`

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch

**Comment by saschagrunert** [comment]
@justaugustus do we want to move forward with this one?

**Comment by hasheddan** [comment]
Do we need to bump timeout on `pull-release-test`?

**Comment by saschagrunert** [comment]
> Do we need to bump timeout on `pull-release-test`?

No the test was failing after prow's rebase. Fixed that in rebased on top of the latest master branch

**Comment by saschagrunert** [comment]
`There were tests whose specified size is too big.` :thinking:

**Comment by saschagrunert** [comment]
Will now increase the test timeout.

**Pull request merged**
