### PR TITLE
kube-cross: Build v1.14.4-1 image

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency
/priority important-soon

#### What this PR does / why we need it:

go1.14.4 is out: https://golang.org/doc/devel/release.html#go1.14

/assign @tpepper @dims @cblecker
cc: @kubernetes/release-engineering

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kube-cross: Build v1.14.4-1 image
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @tpepper @dims @cblecker
cc: @kubernetes/release-engineering

**Comment by dims** [comment]
@liggitt any concerns here with the update to newer go version?

**Comment by liggitt** [comment]
this is just prepping the images, which is no-risk. we're still waiting on a good bbolt release to start using go1.14 images, but this is fine to do in the meantime.

**Pull request merged**
