### PR TITLE
WIP: Include cni source builds into the specs

### PR DESCRIPTION
**Pull request by timothysc**
Includes source build spec for CNI.  

Fixes:  https://github.com/kubernetes/release/issues/324 https://github.com/kubernetes/release/issues/310 https://github.com/kubernetes/release/issues/242

Todo: 
Obsoletes : kubernetes-cni 

What todo with the other plugins and which plugins to include?  
calico, weave ... ?

/cc @mikedanese

### CODE REVIEW

**Comment by timothysc** [comment]
@kubernetes/sig-release-pr-reviews ping.

**Comment by mikedanese** [comment]
Weave installs the cni plugin they need from the daemonset.

**Comment by calebamiles** [comment]
No idea how to review this, @timothysc but I'm entirely willing to merge if @mikedanese things this looks reasonable.

**Comment by timothysc** [comment]
@mikedanese it looked like from the binary that you bundled calico.

**Comment by timothysc** [comment]
k, it looks like calico installs via daemonset too but the operation defaults to /opt when formal packaging guidelines dictate /usr/libexec . 

We should poke @lukemarsden and @luxas as an FYI too.  

e.g. try to make the order of checking cni directories as /usr/libexec then /opt.  

/cc @dgoodwin fyi.

**Comment by luxas** [comment]
Why build from source? Isn't there a very high maintainance burden associated with that?
Now that v0.5.2 supports all platforms; we can just consume those (which I'm planning to implement)

**Comment by timothysc** [comment]
>  Isn't there a very high maintainance burden associated with that? 

No, you can have a build bot do it for the rpm builds.  

For many air-gapped environments it's a hard requirement that they can construct from 0, and downloading binaries from the interwebz is a strictly prohibited.

**Comment by luxas** [comment]
> No, you can have a build bot do it for the rpm builds.

I meant changing/updating the build tasks/steps as the source code you're building evolves...

**Comment by timothysc** [comment]
It's not terrible, but there is a cost there.

**Comment by feiskyer** [comment]
@timothysc 0.6.0 will be supported in next release, see https://github.com/kubernetes/kubernetes/issues/49480

**Comment by timothysc** [comment]
Going to close this due to inaction and no one owning it.

**Pull request closed without merging**
