### PR TITLE
Do NOT --htmlize-md on x.y.0 releases. The notes draft contents are correct as is.

### LINKED ISSUE #299: release note generation mangles markdown links
Comparing the [final version of the release notes](https://github.com/kubernetes/kubernetes/blob/0a13fef494c938d42252e8a6bab7f6273dd91b37/CHANGELOG.md) with [the draft](https://github.com/kubernetes/features/blob/master/release-1.6/release-notes-draft.md) [2] it was noted that markdown links will be rendered incorrectly due to what looks like an automated link to PR. The link generation is also subtly incorrect as some links of the form `github.com/someCompany/someRepo/issues/someIssue` will be rewritten as `github.com/kubernetes/kubernetes/pull/someIssue`.

**cc: @bgrant0607**

### PR DESCRIPTION
**Pull request by david-mcmahon**
/shamecube for not looking into this sooner.

fixes #299 #360

### CODE REVIEW

**Comment by enisoc** [comment]
So it's just that we were running htmlize-md twice in the case of releases with pre-generated relnotes drafts?

@roycaihw Can you make the corresponding change in the new implementation?

**Comment by david-mcmahon** [comment]
@enisoc the draft release notes are already htmlized in place by whoever creates/edits that file, so there's no need to do it again and doing it again creates the clobbering/dup'ing effect.

**Comment by roycaihw** [comment]
@enisoc Done.

**Comment by xiangpengzhao** [comment]
:+1:

**Pull request merged**
