### PR TITLE
Build go1.18 and go1.19 variants for release-1.23 and release-1.24

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds 1.23 builder images with go1.18 and go1.19, and 1.24 builder images with go1.19

#### Which issue(s) this PR fixes:

Related to 
* https://github.com/kubernetes/kubernetes/pull/113956
* https://github.com/kubernetes/kubernetes/pull/113983
* https://github.com/kubernetes/kubernetes/issues/112408#issuecomment-1291152712

#### Does this PR introduce a user-facing change?

```release-note
Build Go 1.19.4 and 1.18.9 based images for release-1.23 and release-1.24
```

### CODE REVIEW

**Comment by cpanato** [comment]
I might be missing something, but why do we need those images?

**Comment by liggitt** [comment]
> I might be missing something, but why do we need those images?

This is in service of keeping supported kubernetes branches on supported go versions (go1.19+ as of February 2023). Context links are in the description. 

> ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1

huh… do I have to merge and promote one set of images before adding the kube-cross images? I was trying to mimic other bumps but maybe I crossed streams with multiple PRs

**Comment by xmudrii** [comment]
> huh… do I have to merge and promote one set of images before adding the kube-cross images? I was trying to mimic other bumps but maybe I crossed streams with multiple PRs

Yes, you’re right. You first have to build and promote kube-cross, go-runner, and releng-ci, and then proceed with k8s-cloud-builder and k8s-ci-builder in another PR.

I strongly recommend creating a new GitHub issue in this repo using the Go updates template. It has all the steps needed to update Go in this repo, k/k, and k/test-infra.

**Comment by cpanato** [comment]
@liggitt ah that means we will upgrade the past branches with the latest go and not keep that running with older go releases.
ok got it.

I can do the work if you want to offboard you. let me know.

But do we need to build go1.18 then, why not just upgrade that straight to go1.19

**Comment by liggitt** [comment]
> @xmudrii:
> I strongly recommend creating a new GitHub issue in this repo using the Go updates template. It has all the steps needed to update Go in this repo, k/k, and k/test-infra.

Thanks, spawned https://github.com/kubernetes/release/issues/2822

> @cpanato:
> ah that means we will upgrade the past branches with the latest go and not keep that running with older go releases. ok got it.

that's the goal... it's different than what we've done in the past, but with go moving to more backwards-compatible minor versions in 2023, and with the 

> I can do the work if you want to offboard you. let me know.

That would be excellent, I'd love for someone familiar with the release image side of things to help navigate this. Since updating go minor versions on a release branch is sort of blazing new ground, let's work together to figure out if there are any tweaks to the normal go patch bump checklist needed to straddle minors safely while transitioning.

> But do we need to build go1.18 then, why not just upgrade that straight to go1.19

The release-1.23 PR (https://github.com/kubernetes/kubernetes/pull/113416) moves through go1.18 on the way to go1.19... it seemed like a good idea to have the base/builder images for 1.23+go1.18 available if we needed them, but I guess we could make them on demand if needed later.

**Comment by liggitt** [comment]
/close
in favor of https://github.com/kubernetes/release/issues/2822

**Pull request closed without merging**
