### PR TITLE
hack: Improve comment on 'docker-container' driver usage for buildx

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Resolves review comment stream from https://github.com/kubernetes/release/pull/1511#discussion_r481118862.
/assign @xmudrii @saschagrunert @cpanato 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/test pull-release-cluster-up
(this is taking long than it should)

**Pull request merged**
