### PR TITLE
Set up kubernetes tree in a valid go path.

### PR DESCRIPTION
**Pull request by ixdy**
Fixes a part of kubernetes/kubernetes#36843.

cc @saad-ali

### CODE REVIEW

**Comment by saad-ali** [comment]
Won't this wipe out user's local kubernetes directory/changes?

**Comment by ixdy** [comment]
It shouldn't. All this is doing is changing the path we check out `kubernetes` to.

**Comment by saad-ali** [comment]
LGTM, not sure if you want to wait for @david-mcmahon to take a look otherwise feel free to apply LGTM label.

**Comment by dims** [comment]
LGTM 👍

**Comment by ixdy** [comment]
I just added a commit to check the repo state in `branchff` like we did for anago in #174.

**Comment by ixdy** [comment]
actually, no I didn't, because this is a pull request from the wrong branch. lol.

**Comment by ixdy** [comment]
oh I've ruined everything.

**Comment by ixdy** [comment]
#210 try again

**Pull request closed without merging**
