### PR TITLE
[GO] build Go 1.17.8 and 1.16.15 images

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Build Go 1.17.8 and 1.16.15 images.

/assign @saschagrunert @xmudrii  @palnabarun @puerco @justaugustus 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

xref #2450 

#### Does this PR introduce a user-facing change?

```release-note
build Go 1.17.8 and 1.16.15 images
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
```
go build k8s.io/release/images/build/go-runner: /usr/local/go/pkg/tool/linux_s390x/compile: signal: segmentation fault (core dumped)
```

**Comment by cpanato** [comment]
> ```
> go build k8s.io/release/images/build/go-runner: /usr/local/go/pkg/tool/linux_s390x/compile: signal: segmentation fault (core dumped)
> ```

this is happens sometimes, I've retrigger one job that failed manually and that passes :/

**Pull request merged**
