### PR TITLE
doc(images): Update images README to improve usability

### PR DESCRIPTION
**Pull request by hickeyma**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Some suggestions for improvement to the doc.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you for the contribution to our docs, @hickeyma! :partying_face: 

/lgtm

**Comment by hickeyma** [comment]
Thanks for the review and merge @saschagrunert

**Pull request merged**
