### PR TITLE
spdx: Support archives as package src, autonamespace and other improvements

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind bug
/kind cleanup
/kind feature
/kind deprecation

#### What this PR does / why we need it:

This PR adds a bunch of improvements to the bom tool and the spdx libraries:

* Adds a few more unit tests to the `spdx` package to cover the following functions:
  * `spdx.GetImageReferences`
  * `spdx.TestPullImagesToArchive`
  * `spdx.TestGetDirectoryTree`
  * `spdx.TestIgnorePatterns`
* The `--tarballs` flag is now deprecated. It has been replaced with `--image-archive` during demos and chats, it proved to be confusing (it still works but will print a warning)
* There is a new flag `--archive` that adds archives (currently tars) as packages. Its files are license-scanned and listed in the package
* Passing a flag defining the SPDX document namespace is not required anymore. The generator now defines it using the spdx.org public URL defined in the spec

#### Special notes for your reviewer:

/cc @kubernetes/release-engineering  @kubernetes/release-managers 
/milestone v1.23

#### Does this PR introduce a user-facing change?

```release-note
* Added a few more unit tests to the `spdx` package to cover the following functions: `spdx.GetImageReferences` `spdx.TestPullImagesToArchive` `spdx.TestGetDirectoryTree` `spdx.TestIgnorePatterns`
* bom: The `--tarballs` flag is now deprecated. It has been replaced with `--image-archive` during demos and chats, it proved to be confusing (it still works but will print a warning)
* bom: There is a new flag: `--archive`. When enabled, bom adds archives (currently tars) as spdx packages to the doc. Its files are license-scanned and listed in the package
* bom: Passing a flag defining the SPDX document namespace is not required anymore. The generator now defines it using the spdx.org public URL defined in the 2.2+ spec.
* The spdx package now supports reading compressed tars 
```

### CODE REVIEW

**Comment by puerco** [comment]
After this patch, sboms can be generated describing tar archives, and the namespace is no longer needed. An example:

This command:
```
bom generate --archive=/home/urbano/Downloads/kubectx_v0.9.3_linux_x86_64.tar.gz
```
Yields:
```
               _      
 ___ _ __   __| |_  __
/ __| '_ \ / _` \ \/ /
\__ \ |_) | (_| |>  < 
|___/ .__/ \__,_/_/\_\
    |_|               

 📂 SPDX Document SBOM-SPDX-86c3b736-b3ca-4221-8499-77e0077714e3
  │ 
  │ 📦 DESCRIBES 1 Packages
  │ 
  ├ spdx-tar-extract-4115187429
  │  │ 🔗 2 Relationships
  │  ├ CONTAINS FILE LICENSE (LICENSE)
  │  └ CONTAINS FILE kubectx (kubectx)
  │ 
  └ 📄 DESCRIBES 0 Files

```

**Comment by puerco** [comment]
Yikes, bitten by the GitHub rate limit again. I'll try to see if I can fix it today.

/test pull-release-integration-test

**Comment by justaugustus** [comment]
Given the migration of `bom` has merged in https://github.com/kubernetes/release/pull/2330, let's re-issue this PR to sigs.k8s.io/bom.
/close

**Pull request closed without merging**
