### PR TITLE
Add do_not_publish to template release note map

### PR DESCRIPTION
**Pull request by wilsonehusin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Adds `do_not_publish` field when creating maps, should have been part of #1846

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

(release notes captured in #1846)

/assign @puerco

### CODE REVIEW

**Comment by wilsonehusin** [comment]
I can't tell what actually failed? 😕 

/retest

**Comment by xmudrii** [comment]
@wilsonehusin It looks like it failed because the `go.sum` file is not up-to-date. Can you try running `go mod tidy` locally and/or eventually rebasing the PR?

/retest
I don't see that you changed anything regarding dependencies, so it's a little bit weird. Let me try retesting again.

**Comment by wilsonehusin** [comment]
```sh
❯ git fetch --all
Fetching upstream
Fetching origin

❯ git rebase upstream/master
Current branch add-do_not_publish-on-map-template is up to date.
```

```sh
❯ go mod tidy
warning: ignoring symlink ~/workspace/go/src/k8s.io/release/pkg/cip/dockerregistry/inventory_test/TestFindManifest/empty
warning: ignoring symlink ~/workspace/go/src/k8s.io/release/pkg/cip/dockerregistry/inventory_test/TestFindManifest/singleton
warning: ignoring symlink ~/workspace/go/src/k8s.io/release/pkg/cip/dockerregistry/inventory_test/TestValidateThinManifestsFromDir/invalid/empty
warning: ignoring symlink ~/workspace/go/src/k8s.io/release/pkg/cip/dockerregistry/inventory_test/TestValidateThinManifestsFromDir/valid/multiple-rebases
warning: ignoring symlink ~/workspace/go/src/k8s.io/release/pkg/cip/dockerregistry/inventory_test/TestValidateThinManifestsFromDir/valid/singleton

❯ echo $?
0
```

seems like I'm also up to date? 🤔 

/retest

**Comment by puerco** [comment]
:thinking:  What's going on here? 
/test pull-release-verify

**Comment by wilsonehusin** [comment]
it looks like all PRs are failing on `pull-release-verify` right now? could it be that Go bump made Bazel upset? 🤔

**Comment by xmudrii** [comment]
I've investigated this a little bit and I think that @wilsonehusin is almost right. It's not related to Bazel, however, we've bumped Go to 1.16rc1 in CI. Apparently, there are some differences in how Go 1.16 handles the `go.sum` file, which causes the CI to fail.

I guess that one of the possible solutions is to grab Go 1.16rc.1, then run `go mod tidy`, and then commit changes, however, I'm not sure are there any other changes needed.

For reference, we're using [the `gcr.io/k8s-staging-releng/releng-ci:latest` image for this job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/release/release-config.yaml#L77). Running `go version` in a container based on this image returns:

```
go version go1.16rc1 linux/amd64
```

Also, running `go mod tidy` in the same container will modify the `go.sum` file in the same way as it's done by the CI job. This is what causes the CI job to fail.

cc @justaugustus @kubernetes/release-engineering

**Comment by wilsonehusin** [comment]
using the commit above (5be3caa) as an experiment to make Prow happy -- if it does work, then I'll drop it and raise a separate PR to make history traceable.

/hold

**Comment by wilsonehusin** [comment]
hmm it passed? this makes me wonder if Prow built the HEAD commit on master with 1.16 or not 🤔 

cc @xmudrii @puerco

**Comment by wilsonehusin** [comment]
let's move `go mod` conversation here: https://github.com/kubernetes/release/pull/1885

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by xmudrii** [comment]
@wilsonehusin Is it okay to remove hold from the PR now that #1885 is merged?

**Comment by wilsonehusin** [comment]
oh yep thanks for the reminder @xmudrii 

/hold cancel

**Pull request merged**
