### PR TITLE
fix type error  in release-notes readme, 

### PR DESCRIPTION
**Pull request by oldthreefeng**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
fix type error 

`-start-sha` ==> `--start-sha`, `-debug`   ==> `--debug` ... 
#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by puerco** [comment]
Thank you for the PR @oldthreefeng!
Could you please add `None` into the release note block of the PR?  We need that to make sure the bot removes the `do-not-merge/release-note-label-needed` label.

/assign

**Comment by oldthreefeng** [comment]
OK， done!

**Comment by puerco** [comment]
Thank you @oldthreefeng !
/lgtm
/approve

**Pull request merged**
