### PR TITLE
Update dependencies and cleanup go.mod

### PR DESCRIPTION
**Pull request by saschagrunert**
Just bumped the deps, removed the `// indirect`s, and did a 

```bash
> go mod tidy
> go mod verify
> ./hack/update-all.sh
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
I'm not sure why golangci-lint now complains, usually the new image should not be used yet, right? :thinking:

**Comment by saschagrunert** [comment]
Ahhh, I updated golangci-lint and my "complain when not able to compile" fix is in. So let's wait here for the new image, then we should be able to make the tests happy here as well.

**Comment by saschagrunert** [comment]
Okay it fails, but I think I should not update the golangci-lint dependency because this should be the same as in repro-infra... Let's give it another try

**Comment by saschagrunert** [comment]
Yes, so now we have the right linter errors here:
```
ERROR: golangci-lint failed
```

**Comment by justaugustus** [comment]
YES!!!
/pony party

**Pull request merged**
