### PR TITLE
[GO] build Go 1.18.2 and 1.17.10 images

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Build Go 1.18.2 and 1.17.10 images.

/assign @saschagrunert @Verolop @xmudrii  @palnabarun @puerco @justaugustus 
cc @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

xref #2520 

#### Does this PR introduce a user-facing change?

```release-note
build Go 1.18.2 and 1.17.10 images
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
@saschagrunert need another lgtm, did a fix :)

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
rate limit, will wait a bit before retriggering

**Pull request merged**
