### PR TITLE
dependencies/logrus: update logrus to v1.6.0

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?
 /kind cleanup

#### What this PR does / why we need it:
Update logrus dependency to [v1.6.0](https://github.com/sirupsen/logrus/tree/v1.6.0) which is the latest available and has the [following changes](https://github.com/sirupsen/logrus/releases/tag/v1.6.0)

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
dependencies/logrus: update logrus to v1.6.0
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Needs rebase.

**Comment by saschagrunert** [comment]
@cpanato we could update it to logrus v1.6.0, which should fix the regression introduced in v1.5.0

**Comment by cpanato** [comment]
@saschagrunert upgrade to 1.6.0

**Pull request merged**
