### PR TITLE
Use markdown template rendering for krel release-notes

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This opens-up the way to remove the previous markdown rendering function
by converting krel release-note to the new API.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @puerco

**Comment by puerco** [comment]
I can scratch that one off my list, thanks @saschagrunert :)

**Pull request merged**
