### PR TITLE
Add container images push to `krel anago push`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This uses more already-existing golang code for pushing the container
images into the staging registry. The manifest validation is also part
of that logic.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/hold
for manual testing
#### Does this PR introduce a user-facing change?

```release-note
Added container images push feature to `krel anago push`
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
#### Manual Test

* :heavy_check_mark: Logs are looking good: https://console.cloud.google.com/cloud-build/builds/78e5042e-5f81-443e-9544-3582c1051810?project=kubernetes-release-test

Container images are available, because they have been verified via skopeo

This is ready for review, PTAL
/hold cancel

**Review by hasheddan — APPROVED** [review]
Nice! Awesome work @saschagrunert :)

/lgtm

**Comment by saschagrunert** [comment]
/assign @justaugustus 
for the blocked paths review :)

**Comment by justaugustus** [comment]
Good stuff!
/lgtm
/approve

**Pull request merged**
