### PR TITLE
[go1.16] Build official images

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

(Part of https://github.com/kubernetes/release/issues/1834.)

go1.16 is out! 🎉 
ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1613509049283800

- kube-cross: Build v1.16.0-1 image
- go-runner: Build v2.3.1-go1.16-buster.0 image
- releng-ci: Build v0.4.0 image
- vulndash: Build v0.4.3-5 image 

/assign @hasheddan @saschagrunert @cpanato @puerco 
cc: @kubernetes/release-engineering 

#### Special notes for your reviewer:

`vulndash` is built for completeness, based on the current `dependencies.yaml`
definitions. The vulndash image will not be promoted.

#### Does this PR introduce a user-facing change?

```release-note
- kube-cross: Build v1.16.0-1 image
- go-runner: Build v2.3.1-go1.16-buster.0 image
- releng-ci: Build v0.4.0 image
- vulndash: Build v0.4.3-5 image 
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/hold until go1.16 images are available

```console
$ crane manifest golang:1.16
2021/02/16 18:15:47 No matching credentials were found, falling back on anonymous
2021/02/16 18:15:48 fetching manifest golang:1.16: GET https://index.docker.io/v2/library/golang/manifests/1.16: MANIFEST_UNKNOWN: manifest unknown; map[Tag:1.16]
```

**Comment by xmudrii** [comment]
Why are we setting version to 1.16 instead of 1.16.0? I’m wondering what will happen once Go 1.16.1 goes out. In that case, I think, but I’m not sure at all, that golang:1.16 image would refer to Go 1.16.1. Wouldn’t we end up using 1.16.1 instead of 1.16.0? Potentially, we could end up using 1.16.0 in some places, and 1.16.1 in some other places.

**Comment by justaugustus** [comment]
> Why are we setting version to 1.16 instead of 1.16.0? I’m wondering what will happen once Go 1.16.1 goes out. In that case, I think, but I’m not sure at all, that golang:1.16 image would refer to Go 1.16.1. Wouldn’t we end up using 1.16.1 instead of 1.16.0? Potentially, we could end up using 1.16.0 in some places, and 1.16.1 in some other places.

@xmudrii -- the Golang team elides "unnecessary" parts of the version string and the upstream Golang images respect the Golang team's versioning.

We pass that version as a build argument, so they have to match.
See my comment here: https://github.com/justaugustus/release/blob/f80510d8093f728e58a1e6859742aee9eb6cce18/dependencies.yaml#L77-L81

When go1.16.1 is released, we add the `.1`.

**Comment by xmudrii** [comment]
@justaugustus — Makes sense, thanks for the explanation!

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
```
denied: Token exchange failed for project 'k8s-staging-build-image'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
```

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@justaugustus @cpanato @saschagrunert something changed on the bucket ACL's?

**Comment by cpanato** [comment]
@dims It is pending some changes in the svcacc @spiffxp will look at it, but did not have time last week, slack 🧵  https://kubernetes.slack.com/archives/CJH2GBF7Y/p1612883834197800

but if reach that point the image was built 😄

**Comment by dims** [comment]
@cpanato Ack thanks!

**Comment by justaugustus** [comment]
/hold cancel

```console
$ crane manifest golang:1.16
2021/02/17 09:05:23 No matching credentials were found, falling back on anonymous
```

```json
{"manifests":[{"digest":"sha256:9db49c57a1b36aa4f3590198142b835e560e63f086bb1447bcb2908300b80e54","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"amd64","os":"linux"},"size":1795},{"digest":"sha256:ea746239e8038c6278a85833647271370d33044a770fbf8ec2af27873fc9691f","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"arm","os":"linux","variant":"v5"},"size":1795},{"digest":"sha256:57aedf2919a733b0a254a57d0d075e0babf70298f58ac4beef46cae4a3e63069","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"arm","os":"linux","variant":"v7"},"size":1795},{"digest":"sha256:eb3d99abe3c9499d590de8e0a5188e226e12002b50e3a9bedce35f0eb25d4457","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"arm64","os":"linux","variant":"v8"},"size":1794},{"digest":"sha256:131eea7b484a6506d415e68204abcd402355c949735caffc120541c194230d5c","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"386","os":"linux"},"size":1796},{"digest":"sha256:9fff36227038b7f2e4a7d9f40ea4fd128ea74a191d1ed9b87ab649e1c34f62de","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"mips64le","os":"linux"},"size":1795},{"digest":"sha256:302c3c2950f8781b40a28fde819ecea26b9536e04e0ac86dc1263eddf1dd0763","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"ppc64le","os":"linux"},"size":1795},{"digest":"sha256:d1ea51c7f51153a69c98fa2d0c7dcd2eb89b5be9fc06fc7d63ea15ea86b651e0","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"s390x","os":"linux"},"size":1795},{"digest":"sha256:331a8b0c1ccb4729c307c67433fd75d0ce9978fa238ab3a7585d74229403c82b","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"amd64","os":"windows","os.version":"10.0.17763.1757"},"size":3401},{"digest":"sha256:b71edb2b21048bac0b745f91f9bc819baf419da67d4cbc20acaca977cedef11e","mediaType":"application\/vnd.docker.distribution.manifest.v2+json","platform":{"architecture":"amd64","os":"windows","os.version":"10.0.14393.4225"},"size":3324}],"mediaType":"application\/vnd.docker.distribution.manifest.list.v2+json","schemaVersion":2}
```

**Pull request merged**
