### PR TITLE
Start kubelet with systemd on package install

### PR DESCRIPTION
**Pull request by rustyrobot**
* Use special helper to enable and start the service.
* It also automatically generates `postinst`,  `postrm`, `prerm` hooks.

Systemd service Debian [packaging guide](https://wiki.debian.org/Teams/pkg-systemd/Packaging).

Closes: #91
Depends-on: #93

### CODE REVIEW

**Comment by errordeveloper** [comment]
LGTM

**Comment by mikedanese** [comment]
Thanks!

**Comment by luxas** [comment]
@rustyrobot This needs a rebase now when your other changes have been merged

**Comment by luxas** [comment]
LGTM

**Pull request merged**
