### PR TITLE
Download zeitgeist binary directly

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We have no need to make zeitgeist part of `go.mod` any more, so we can directly download the binary and use it.

This patch also bumps the release to v0.3.5.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm


need rebase

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
@kubernetes/release-engineering PTAL

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
