### PR TITLE
Update dependencies for new deb and rpm packages

### PR DESCRIPTION
**Pull request by xmudrii**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR ensures dependencies defined for new packages in `metadata.yaml` match dependencies used for building packages hosted in the Google-owned repository.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/assign @Verolop @puerco @jeremyrickard 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by xmudrii** [comment]
As a note: we might want to utilize `dependencies.yaml` and zeitgeist here, but that's for some follow-up.

**Review by jeremyrickard — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
