### PR TITLE
SPDX package unit and integration tests

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR adds the first batch of tests for the `spdx` package. It includes a `spdx_test` package to do integration tests with the fake implementation and a unit test file to test the main functions.

#### Which issue(s) this PR fixes:

Part of #1837

#### Special notes for your reviewer:

Needs https://github.com/kubernetes/release/pull/2064 to run

#### Does this PR introduce a user-facing change?

```release-note
The SPDX package now has unit and integration tests 
```

### CODE REVIEW

**Comment by puerco** [comment]
Oops I had forgotten to regenerate the fakes.

**Review by justaugustus — APPROVED** [review]
Thanks @puerco!

**Pull request merged**
