### PR TITLE
Migrate vulnerability dashboard (vulndash) to k/release

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Migrate [vulnerability dashboard](https://github.com/kubernetes-sigs/k8s-container-image-promoter/tree/master/dashboard) to k/release
- OWNERS: Add reviewers/approvers for vulndash
- vulndash: Use k8s.io/release import
- vulndash: Use klog v2 (and run go mod tidy)
- vulndash: Convert to cobra 
- pkg/vulndash: Clean up lint warnings
- images: Add dir for k8s-staging-artifact-promoter project

#### Special notes for your reviewer:

FYI @cpanato. Still a WIP, but I'm going to hack on this a bit to fix that vuln-update test.

Image building will need to be fixed in a follow-up, as `pkg/vulndash` is not yet `go get`-able from this repo.
Please ignore `images/artifact-promoter/vulndash` in review.

#### Does this PR introduce a user-facing change?

```release-note
- Migrate vulnerability dashboard (vulndash) to k/release
```

### CODE REVIEW

**Comment by puerco** [comment]
Ring if we can help!

**Comment by justaugustus** [comment]
Ready for review!

/assign @saschagrunert @cpanato @hasheddan @xmudrii
cc: @kubernetes/release-engineering 

Please note the following during review:

> Image building will need to be fixed in a follow-up, as `pkg/vulndash` is not yet `go get`-able from this repo.
> Please ignore `images/artifact-promoter/vulndash` in review.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Companion PR is here: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/276

**Review by cpanato — COMMENTED** [review]
too late to the party
/lgtm

**Comment by feiskyer** [comment]
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: k8s-artifacts-prod-vuln-dashboard/dashboard.html</Details>
</Error>
```

Has the link changed?

**Pull request merged**
