### PR TITLE
Use testify require instead of assert

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Require stops execution when a test fails which is the more used package
in our repository. To have a unique look and feel of the tests we now
stick to the require package.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by justaugustus** [comment]
@saschagrunert -- Needs rebase

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch

**Comment by saschagrunert** [comment]
```
WARNING: Download from https://pypi.python.org/packages/source/s/six/six-1.12.0.tar.gz failed: class java.io.IOException GET returned 503 Backend is unhealthy
```
/retest

**Pull request merged**
