### PR TITLE
schedule-builder: add new field

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

While updating the patch schedule for this PR https://github.com/kubernetes/website/pull/28971 notice that we have a new field called `note` and the schedule-builder weas failing.

Adding the notes field and the schedule was generated using this patch

/assign @saschagrunert @puerco 
cc @kubernetes/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
schedule-builder: add new field
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you for following up on this! :pray:

**Comment by cpanato** [comment]
@saschagrunert fixed the tests 😅

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
more tests, I should run it before pushing 😓

**Comment by cpanato** [comment]
@saschagrunert can I have a lgtm?

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
