### PR TITLE
Rename `SetReleaseVersion` to be `GetBuildVersion`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This should make it's usage intention more clear. The function now also
does not use the `parentBranch` argument any more, but just a bool
indicating if we're going to create a new branch from the master. Some
other refactorings around internal variables have been applied, too.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Note: rename to `GenerateReleaseVersion`

**Review by hasheddan — COMMENTED** [review]
@saschagrunert should this have a release note?

**Comment by tpepper** [comment]
> Note: rename to `GenerateReleaseVersion`

Since the outcome isn't necessarily a "release" that isn't fully descriptive as Stephen noted.

What do folks think about "SetBuildVersion"?  We're doing a building action.  We know we sometimes need humans to be able to override a generated version, so "generate" might not be fully descriptive.

**Comment by tpepper** [comment]
Or separate functions for Set and Generate?  Or Override and Generate?

**Comment by saschagrunert** [comment]
@tpepper @justaugustus how about `GetBuildVersion()`? (current state)

**Review by justaugustus — CHANGES_REQUESTED** [review]
> > Note: rename to `GenerateReleaseVersion`
> 
> Since the outcome isn't necessarily a "release" that isn't fully descriptive as Stephen noted.
> 
> What do folks think about "SetBuildVersion"? We're doing a building action. We know we sometimes need humans to be able to override a generated version, so "generate" might not be fully descriptive.

> @tpepper @justaugustus how about `GetBuildVersion()`? (current state)


@saschagrunert @tpepper -- Seems like the intention is still a bit muddied.

I still prefer `[Generate|Set]ReleaseVersion(s)?` here.

A few notes:
- whichever function name we land on, the command should be a subcommand of `krel anago` (so that we know it's only going to be used for shell anago):

  ```shell
  krel anago generate-release-versions
  ```

- this command takes a build version as input, presumably via the `--build-version` flag.
  When we say "build version", we're referring to artifacts output from a `ci-kubernetes-build**` periodic job.
  It would be inaccurate/confusing here to also refer to the final release versions that we generate here as "build versions".

**Comment by saschagrunert** [comment]
Okay, I renamed it to `GenerateReleaseVersion` and also changed all docs as well as the `krel anago` subcommand name.

**Comment by saschagrunert** [comment]
> * this command takes a build version as input, presumably via the `--build-version` flag.
>   When we say "build version", we're referring to artifacts output from a `ci-kubernetes-build**` periodic job.
>   It would be inaccurate/confusing here to also refer to the final release versions that we generate here as "build versions".

I'm confused now, should we rename this flag to something else? :thinking:

**Pull request merged**
